### PR TITLE
Updating firebase-event-proxy/pom.xml and parent pom.xml.

### PR DESCRIPTION
**Pull request by misterwilliam**
Updating firebase-event-proxy/pom.xml so that it is more like other pom's and references the parent pom.xml. Adding firebase-event-proxy to parent pom.xml.

Will work on tests next.

### CODE REVIEW

**Comment by lesv** [comment]
A few checkstyle issues:

```
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:17:9: error: Package name 'com.example.GaeFirebaseEventProxy' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:30: error: Import statement for 'com.fasterxml.jackson.core.JsonProcessingException' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:31: error: Import statement for 'com.fasterxml.jackson.databind.ObjectMapper' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:32: error: Import statement for 'com.firebase.client.AuthData' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:33: error: Import statement for 'com.firebase.client.DataSnapshot' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:34: error: Import statement for 'com.firebase.client.Firebase' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:35: error: Import statement for 'com.firebase.client.FirebaseError' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:36: error: Import statement for 'com.firebase.client.ValueEventListener' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:37: error: Import statement for 'com.firebase.security.token.TokenGenerator' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:38: error: Import statement for 'com.google.appengine.api.utils.SystemProperty' is in the wrong order. Should be in the 'THIRD_PARTY_PACKAGE' group, expecting not assigned imports on this line.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:52: error: Abbreviation in name must contain no more than '1' capital letters.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/FirebaseEventProxy.java:52:12: error: Local variable name 'FIREBASE_LOCATION' must match pattern '^[a-z][a-zA-Z0-9]*$'.
/home/travis/build/GoogleCloudPlatform/java-docs-samples/appengine/firebase-event-proxy/gae-firebase-event-proxy/src/main/java/com/example/GaeFirebaseEventProxy/ServletContextListenerImpl.java:17:9: error: Package name 'com.example.GaeFirebaseEventProxy' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'.
```

Please fix and it otherwise appears Ok to merge. (once travis passes)

**Comment by tswast** [comment]
Note: You can run `mvn clean verify -DskipTests` to run the build and
checkstyle without running the tests.

*  •  **Tim Swast*
*  •  *Developer Programs Engineer
*  •  *Google Cloud DevRel
*  •  *swast@google.com
  •  +1 (512) 343-5226

**Comment by misterwilliam** [comment]
@lesv This PR is ready for another look.

**Comment by lesv** [comment]
LGTM

**Pull request merged**
