### PR TITLE
Fix compilation failure when running mvn clean package -DskipTests

### PR DESCRIPTION
**Pull request by jakubrauch**
InspectImageFile sample was failing to compile when running `mvn clean package -DskipTests` as instructed in README. Updated the method to pass sample arguments in the same way as in
`RedactImageFile`. Rebuilt successfully.

### CODE REVIEW

**Comment by lesv** [comment]
Java 8 failing

**Comment by lesv** [comment]
It's a flaky test:
```
java.lang.AssertionError:

Expected: a string containing "PHONE_NUMBER"
     but: was "Job created with ID:projects/java-docs-samples-testing/dlpJobs/i-1602130357019026859
Unable to verify job completion.
Job status: RUNNING
No findings.
"
	at com.example.dlp.InspectIT.testDatastoreInspectionReturnsInfoTypes(InspectIT.java:97)
```

**Comment by lesv** [comment]
```
******************** TESTING PROJECTS ********************
------------------------------------------------------------
- testing dlp
------------------------------------------------------------
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 188.913 s <<< FAILURE! - in com.example.dlp.InspectIT
[ERROR] testDatastoreInspectionReturnsInfoTypes(com.example.dlp.InspectIT)  Time elapsed: 65.181 s  <<< FAILURE!
java.lang.AssertionError:

Expected: a string containing "PHONE_NUMBER"
     but: was "Job created with ID:projects/java-docs-samples-testing/dlpJobs/i-1602130357019026859
Unable to verify job completion.
Job status: RUNNING
No findings.
"
	at com.example.dlp.InspectIT.testDatastoreInspectionReturnsInfoTypes(InspectIT.java:97)

[ERROR] testGcsFileInspectionReturnsInfoTypes(com.example.dlp.InspectIT)  Time elapsed: 61.704 s  <<< FAILURE!
java.lang.AssertionError:

Expected: a string containing "PHONE_NUMBER"
     but: was "Job created with ID:projects/java-docs-samples-testing/dlpJobs/i-7380970085939023990
Unable to verify job completion.
Job status: RUNNING
No findings.
"
	at com.example.dlp.InspectIT.testGcsFileInspectionReturnsInfoTypes(InspectIT.java:75)

[ERROR] testBigqueryInspectionReturnsInfoTypes(com.example.dlp.InspectIT)  Time elapsed: 61.943 s  <<< FAILURE!
java.lang.AssertionError:

Expected: a string containing "PHONE_NUMBER"
     but: was "Job created with ID:projects/java-docs-samples-testing/dlpJobs/i-7029944876551768183
Unable to verify job completion.
Job status: RUNNING
No findings.
"
	at com.example.dlp.InspectIT.testBigqueryInspectionReturnsInfoTypes(InspectIT.java:119)

[ERROR] Failures:
[ERROR]   InspectIT.testBigqueryInspectionReturnsInfoTypes:119
Expected: a string containing "PHONE_NUMBER"
     but: was "Job created with ID:projects/java-docs-samples-testing/dlpJobs/i-7029944876551768183
Unable to verify job completion.
Job status: RUNNING
No findings.
"
[ERROR]   InspectIT.testDatastoreInspectionReturnsInfoTypes:97
Expected: a string containing "PHONE_NUMBER"
     but: was "Job created with ID:projects/java-docs-samples-testing/dlpJobs/i-1602130357019026859
Unable to verify job completion.
Job status: RUNNING
No findings.
"
[ERROR]   InspectIT.testGcsFileInspectionReturnsInfoTypes:75
Expected: a string containing "PHONE_NUMBER"
     but: was "Job created with ID:projects/java-docs-samples-testing/dlpJobs/i-7380970085939023990
Unable to verify job completion.
Job status: RUNNING
No findings.
"
[ERROR] Tests run: 22, Failures: 3, Errors: 0, Skipped: 0
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M3:verify (default) on project dlp-samples: There are test failures.
```

**Comment by lesv** [comment]
@jakubrauch @pheonixblade9 I'm willing to accept this since the test is marked as flaky, but I'd like both of you to chime in this fixes the problem.

**Comment by lesv** [comment]
I appear to have merged.  (not sure that's was my goal, but ok.

**Comment by jakubrauch** [comment]
Thanks Les, the change fixes compilation failure and integ tests are unrelated to this particular fix

**Pull request merged**
