### PR TITLE
chore: Update ownership of Retail samples

### PR DESCRIPTION
**Pull request by kweinmeister**
The Cloud Retail team is supporting the Retail samples. Updating CODEOWNERS to reflect that.

Fixes #issue

> It's a good idea to open an issue first for discussion.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Review by lesv — APPROVED** [review]

**Review by lesv — CHANGES_REQUESTED** [review]
There is an error warning from Github.

**Review by lesv — COMMENTED** [review]
```
Unknown owner on line 15: make sure @gcseh exists and has write access to the repository
…ot/                           @gcseh @GoogleCloudPlatform/api-iot @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Unknown owner on line 16: make sure the team @GoogleCloudPlatform/dee-platform-ops exists and has write access to the repository
…ogging/                       @GoogleCloudPlatform/dee-platform-ops @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Unknown owner on line 17: make sure the team @GoogleCloudPlatform/api-pubsub-and-pubsublite exists and has write access to the repository
…ubsub/                        @GoogleCloudPlatform/api-pubsub-and-pubsublite @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Unknown owner on line 18: make sure the team @GoogleCloudPlatform/api-pubsub-and-pubsublite exists and has write access to the repository
…ubsublite/                    @GoogleCloudPlatform/api-pubsub-and-pubsublite @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Unknown owner on line 19: make sure the team @GoogleCloudPlatform/cloud-storage-dpes exists and has write access to the repository
…torage/**/*.java              @GoogleCloudPlatform/cloud-storage-dpes @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Invalid owner on line 20:
… @googleapis/github-automation/ @sofisl @GoogleCloudPlatform/java-samples-reviewers
Unknown owner on line 21: make sure the team @GoogleCloudPlatform/dee-infra exists and has write access to the repository
…sset/                         @GoogleCloudPlatform/dee-infra @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Unknown owner on line 22: make sure the team @GoogleCloudPlatform/dee-platform-ops exists and has write access to the repository
…rrorreporting/                @GoogleCloudPlatform/dee-platform-ops @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Unknown owner on line 23: make sure the team @GoogleCloudPlatform/dee-platform-ops exists and has write access to the repository
…onitoring/                    @GoogleCloudPlatform/dee-platform-ops @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Unknown owner on line 24: make sure the team @GoogleCloudPlatform/cloud-retail-team exists and has write access to the repository
…etail/                        @GoogleCloudPlatform/cloud-retail-team @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
```

**Review by averikitsch — APPROVED** [review]
Future updates: We need to find another team within GCP org to replace @googleapis/github-automation. We also need to update @gcseh to a team using team sync.

**Comment by averikitsch** [comment]
> Member

I've added these teams as repo collaborators

**Review by lesv — CHANGES_REQUESTED** [review]
It's now down to two problems:

```
Unknown owner on line 15: make sure @gcseh exists and has write access to the repository
…ot/                           @gcseh @GoogleCloudPlatform/api-iot @GoogleCloudPlatform/java-samples-reviewers @yoshi-approver
Invalid owner on line 20:
… @googleapis/github-automation/ @sofisl @GoogleCloudPlatform/java-samples-reviewers
```

**Comment by lesv** [comment]
@sofisl Are you still wanting to approve changes here?

**Comment by lesv** [comment]
@gcseh Do you still need to approve this stuff?

**Review by lesv — APPROVED** [review]

**Pull request merged**
