### PR TITLE
chore(storage): move storage/s3-sdk into a proper package

### PR DESCRIPTION
**Pull request by kurtisvg**
Fixes #issue

> It's a good idea to open an issue first for discussion.

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [x] `pom.xml` parent set to latest `shared-configuration`
- [x] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Review by tritone — APPROVED** [review]
Since the samples are moving directories, I guess we should follow up with docs as well? @JesseLovelace @frankyn @BenWhitehead

**Review by lesv — APPROVED** [review]

**Comment by lesv** [comment]
# Java 11
```

#
# storage/s3-sdk
#

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.153 s <<< FAILURE! - in storage.s3sdk.ListGcsObjectsTest
[ERROR] storage.s3sdk.ListGcsObjectsTest.testListObjects  Time elapsed: 3.04 s  <<< ERROR!
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
 ```

**Comment by tritone** [comment]
> # Java 11
> ```
> 
> #
> # storage/s3-sdk
> #
> 
> [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.153 s <<< FAILURE! - in storage.s3sdk.ListGcsObjectsTest
> [ERROR] storage.s3sdk.ListGcsObjectsTest.testListObjects  Time elapsed: 3.04 s  <<< ERROR!
> com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
> ```

This failure has been happening consistently-- @BenWhitehead is going to work on a fix.

**Comment by frankyn** [comment]
@tritone please file a bug with the documentation team and they can help us update the paths, but you're correct in that we need to update public documentation with this change.

**Comment by tritone** [comment]
> @tritone please file a bug with the documentation team and they can help us update the paths, but you're correct in that we need to update public documentation with this change.

@kurtisvg made a CL to do the docs fix as well; he will push once this is merged.

**Pull request closed without merging**
