### PR TITLE
Fix checkstyle errors in XMPP sample.

### PR DESCRIPTION
**Pull request by tswast**
Add XMPP sample to Travis build, added in https://github.com/GoogleCloudPlatform/java-docs-samples/pull/182.

### CODE REVIEW

**Comment by tswast** [comment]
@lesv PTAL
@meteatamel FYI

**Comment by meteatamel** [comment]
Thanks for fixing the checkstyle warnings. For future reference, where can I see these warnings myself?

**Comment by tswast** [comment]
@metea Run `mvn clean verify` instead of `mvn clean test`. Checkstyles are done in the "verify" build phase, which happens after the tests pass.

**Comment by lesv** [comment]
Argh - I should have noticed at least one of those -- Thanks.

LGTM

**Pull request merged**
