### PR TITLE
dialogflow: remove unused samples and tests

### PR DESCRIPTION
**Pull request by Strykrol**
Tests are currently unaltered, as the tests have variable dependencies. An example being the `listContexts` function stores a count into a `contexts` variable, which is then used to verify `deleteContext` functions as expected. 

If I can get help refactoring test files that would be great. Otherwise, I will take a stab at them later this week.

### CODE REVIEW

**Comment by lesv** [comment]
A lot of ML samples need to be very loosely tested as the technology often changes underneath us.
I put a "do not merge" tag until you get the tests back.

**Comment by lesv** [comment]
Apparently I wasn't thinking when I commented yesterday.

**Comment by nnegrey** [comment]
Assigning to myself to get the tests updated for these.

**Comment by nnegrey** [comment]
@Strykrol should there be more deletions than just the list methods? 
I'm gonna break up the tests into individual files.

**Comment by nnegrey** [comment]
@Strykrol, um mind pulling down the latest changes then just merging in master to the branch?

I was trying to do it, but just ended up creating a new branch on here. https://github.com/GoogleCloudPlatform/java-docs-samples/tree/Strykrol-snippetCleanup

**Comment by nnegrey** [comment]
Closing, something got lost in this PR and the tests are not finishing. 
I've opened this one https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2602 that I can directly edit.

**Pull request closed without merging**
