### PR TITLE
[Secret Manager] Updated samples with etag support

### PR DESCRIPTION
**Pull request by gwhitehawk**
Fixes #issue

> It's a good idea to open an issue first for discussion.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by shubha-rajan** [comment]
Hi @gwhitehawk thanks for the PR! It looks like there are some merge conflicts. Please resolve those, and then I'll review your changes.

**Comment by lesv** [comment]
I suspect this has been eating our quota.  Can't run secretManager tests until tomorrow.

**Comment by shubha-rajan** [comment]
> I suspect this has been eating our quota. Can't run secretManager tests until tomorrow.

I don't think we've run tests with this PR yet. It's still waiting on someone to add the `kokoro-force-run` label, which I haven't done since tests are guaranteed to fail because of the merge conflicts.

**Comment by gwhitehawk** [comment]
Closing pull request, it seems I was working on my old repo fork accidentally.

**Pull request closed without merging**
