### PR TITLE
Remove PowerMock from the Slack GCF sample.

### PR DESCRIPTION
**Pull request by eamonnmcmanus**
Instead of using Whitebox, use package-private constructor overloads
to supply the values needed by the test.

### CODE REVIEW

**Comment by eamonnmcmanus** [comment]
I don't know how to test this properly, so I'm unable to validate the changes. I think the sample should probably have instructions.

**Comment by lesv** [comment]
@ace-n PTAL

**Comment by lesv** [comment]
That works, there may be some minor indicator that somethng is missing, but it works.

**Comment by ace-n** [comment]
*Update:* I probably don't have time to work on this unless the  _existing_ tests are failing.

@lesv / @saturnism - can one of you help Eamonn get the modified test passing?

**Comment by lesv** [comment]
@eamonnmcmanus It looks like there is some merge conflict - if you fix that, I can help figure out what's failing.

**Comment by eamonnmcmanus** [comment]
I may have resolved the merge conflict, or I may have borked this PR. I'm not sure whether I should really have pushed 237 commits, even if they were just from the merge. The CLA message makes me think not.

**Comment by eamonnmcmanus** [comment]
This isn't important enough to spend more time on.

**Comment by saturnism** [comment]
@eamonnmcmanus i cherry picked the commit and created a new branch/pr based on your code, but also rebased to the latest head/trunk.  ptal https://github.com/GoogleCloudPlatform/java-docs-samples/pull/3186

**Pull request closed without merging**
