### PR TITLE
feat(appengine): Gradle on java21 helloworld

### PR DESCRIPTION
**Pull request by suztomo**
Based on https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9432 (which is now merged), adding Gradle files.

## Description

Background b/342640585.

## Checklist

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [x] `pom.xml` parent set to latest `shared-configuration`
- [x] Appropriate changes to README are included in PR
- [x] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [x] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] **Tests** pass:   `mvn clean verify` **required**
- [x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [x] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
  - `mvn -P lint clean compile pmd:cpd-check spotbugs:check` fails with `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project helloworld-jdk21: Fatal error compiling: error: invalid target release: 21 -> [Help 1]`. However because this hello-world sample is targeted for Java 21, this is no problem.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by suztomo** [comment]
All checks have passed!

**Comment by suztomo** [comment]
@telpirion Would you review this too? This is similar to https://github.com/GoogleCloudPlatform/java-docs-samples/pull/9432, but adding Gradle build file example.

**Comment by srinjoyray** [comment]
Hi @suztomo, are you building everything through gradle and able to successfully run and deploy the application?
An older version of GAE JARs (2.0.23) are getting used.  We should update those to the latest version (2.0.30).

**Comment by suztomo** [comment]
> are you building everything through gradle and able to successfully run and deploy the application?

Yes, it builds with Gradle and successfully deploys the app ([screenshot](https://screenshot.googleplex.com/A95XK4h3C6Yt5Qv.png)). 

I just updated the appengine plugin library version to 2.0.30.

**Review by telpirion — APPROVED** [review]

**Pull request merged**
