### PR TITLE
Update Endpoints Migration Sample

### PR DESCRIPTION
**Pull request by frankyn**
PR to update Endpoints Migration Sample

Changes

- Updated README
  - updated legacy documentation links to new location  `https://cloud.google.com/endpoints/docs/frameworks/legacy/v1/java`
  -  called out discovery document in README
- Updated dependency/plugin versions 
- Added migration sample to appengine/pom.xml

### CODE REVIEW

**Comment by frankyn** [comment]
Failure was related to Vision sample.

**Comment by lesv** [comment]
@gguuss Can you look at the flaky vision sample?  Frank ok to merge.

**Comment by gguuss** [comment]
@lesv @frankyn Vision tests are passing for me, but I'll take a closer look at the build break.

**Comment by lesv** [comment]
@gguuss Thanks for looking, but it's sounding like there is a flaky test.

**Comment by gguuss** [comment]
@lesv The test failed from local file then succeeded from GCS with the same image. Now I'm seeing (rarely) "image processing" errors from the API, e.g.:

```
   detectWebAnnotationsGcs(com.example.vision.DetectIT)  Time elapsed: 6.69 sec  <<< FAILURE!
    java.lang.AssertionError:
    Not true that <"Error: image-annotator::Web detection error.: Image processing error!
"> contains <"Palace">
    	at com.example.vision.DetectIT.detectWebAnnotationsGcs(DetectIT.java:249)
    Caused by: java.lang.AssertionError:
    Not true that <"Error: image-annotator::Web detection error.: Image processing error!
"> contains <"Palace">
    	at com.example.vision.DetectIT.detectWebAnnotationsGcs(DetectIT.java:249)
```

I'm not sure these are specific to the tests or the sample and I'm not seeing error codes in the console. 

I'm occasionally seeing:

```
Not true that <"Error: image-annotator::error(12): We can not access the URL currently. Please download the image and pass it in.
"> contains <"Palace of Fine Arts">
	at com.example.vision.DetectIT.testLandmarksUrl(DetectIT.java:132)
Caused by: java.lang.AssertionError:
Not true that <"Error: image-annotator::error(12): We can not access the URL currently. Please download the image and pass it in.
"> contains <"Palace of Fine Arts">
	at com.example.vision.DetectIT.testLandmarksUrl(DetectIT.java:132)
```

As well, this does seem to happen more frequently on landmarks GCS URI.

**Comment by gguuss** [comment]
Hopefully [PR 663](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/663) resolves our flaky test.

**Pull request merged**
