### PR TITLE
Update the Public data set name

### PR DESCRIPTION
**Pull request by AlirezaSaberi**
The old dataset name is not valid anymore and causes an iternal error

### CODE REVIEW

**Comment by AlirezaSaberi** [comment]
I signed it!

**Comment by AlirezaSaberi** [comment]
I signed it!

**Comment by AlirezaSaberi** [comment]
I signed it!

**Comment by jabubake** [comment]
@AlirezaSaberi  can you confirm that you used the same email address to sign the CLA as you did to author this PR ?

**Comment by lesv** [comment]
@AlirezaSaberi Thank you for the change -- I see you have two github accounts, I've checked both of them and neither has signed the CLA.   Once you sign, we can accept your contribution.

**Comment by AlirezaSaberi** [comment]
@lesv  I have signed the CLA four days ago with my gmail account [http://i68.tinypic.com/2ezpsoj.png](url).

**Comment by lesv** [comment]
Wow - that to CLA bot awhile.  Sorry for the trouble and thanks for your submission.

**Pull request merged**
