### PR TITLE
Add snippet for getCollections()

### PR DESCRIPTION
**Pull request by samtstern**

### CODE REVIEW

**Comment by samtstern** [comment]
@jabubake can you assign the appropriate reviewer here?

**Comment by samtstern** [comment]
Thanks!  What's up with Kokoro?

**Comment by jabubake** [comment]
@samtstern : not sure. @kurtisvg any clue ?

**Comment by lesv** [comment]
You need to add the tag `kokoro:run` or `kokoro:force-run` for fork'd PR's.  (so you can inspect the code first before running on Kokoro.

**Comment by samtstern** [comment]
@lesv looks like you and @kokoro-team need to work out your differences haha

**Comment by lesv** [comment]
@samtstern It's actually a security feature, it lets us accept PR's from anyone, and only run code after we review it.  It let's us work on a branch will full features.

**Comment by samtstern** [comment]
@lesv I mean that you added the `kokoro:force-run` label but it was immediately removed.

**Comment by lesv** [comment]
Ah, but @samtstern that means it also started the build.  It's the way Kokoro works, you set it, it does the action and clears the flag so you can set it again.

**Comment by samtstern** [comment]
@lesv cool thanks for the explanation!

**Comment by samtstern** [comment]
@jabubake I fixed test failures could you add the `kokoro` label?

**Pull request merged**
