### PR TITLE
healthcare API: add ascending order to DICOMweb tests

### PR DESCRIPTION
**Pull request by noerog**
Fixes https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3845

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [x] `pom.xml` parent set to latest `shared-configuration`
- [x] **Tests** pass:   `mvn clean verify` **required**
- [x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Review by averikitsch — APPROVED** [review]
It's not great that these tests are order dependent

**Comment by noerog** [comment]
Is it possible to bypass the "MethodName: Method name 'z_test_DicomWebDeleteStudy' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'." Lint error?

**Comment by lesv** [comment]
`@SupressWarnings("checkstyle:MethodName")` might work.

**Comment by lesv** [comment]
https://stackoverflow.com/questions/4023185/how-to-disable-a-particular-checkstyle-rule-for-a-particular-line-of-code

**Pull request merged**
