### PR TITLE
Move samples added in managedvms to managed_vms

### PR DESCRIPTION
**Pull request by ludoch**

### CODE REVIEW

**Comment by lesv** [comment]
Please make sure to check w/ Mark before merging.

**Comment by lesv** [comment]
IMPORTANT - Please make sure Mark approves, as these URL's are in the docs.

**Comment by ludoch** [comment]
I can do an internal CL and we sync up both updates.

**Comment by ludoch** [comment]
cr/113991856

**Comment by lesv** [comment]
Mark Approves of doing this - still work in various CL's.

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
Les wondering why Tavis hasn't run.

**Pull request merged**
