### PR TITLE
feat: use LazySpannerInitializer instead of DCL

### LINKED ISSUE #2862: Functions - Java Spanner example uses DCL
## Describe the issue

GCF Java 11 [Spanner sample]( https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/functions/spanner/src/main/java/functions/HelloSpanner.java#L59) uses Double checked locking.  The pattern is known to be broken, should follow the [lazy field init example](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/functions/concepts/lazy-fields/src/main/java/functions/LazyFields.java)

### PR DESCRIPTION
**Pull request by olavloite**
The Spanner client library now includes a lazy initializer for Spanner instances that can be used with Google Cloud Functions and other libraries that want to create an instance the first time one is needed and reuse this instance for subsequent requests.

Fixes #2862

### CODE REVIEW

**Comment by olavloite** [comment]
cc @saturnism

**Review by thiagotnunes — APPROVED** [review]
LGTM

**Comment by saturnism** [comment]
thanks! /cc @ace-n

**Review by ace-n — APPROVED** [review]
I like how much cleaner this looks 👍 

(I don't believe I own the `spanner` GCF samples though, since they're not "strictly for GCF".)

**Review by lesv — APPROVED** [review]

**Pull request merged**
