### PR TITLE
KMS: fixes the kms failing tests.

### PR DESCRIPTION
**Pull request by White0ut**
Fix the tests introduced in #816.

Some code was still calling encrypt(...) with a key version.

### CODE REVIEW

**Comment by White0ut** [comment]
weird, commits from my personal machine weren't picked up by Google CLA. Should be fixed now.

**Comment by lesv** [comment]
Thanks.

**Comment by lesv** [comment]
Well, it didn't quite make it.  Something I should do?

```
[INFO] Building kms-samples 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kms-samples ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ kms-samples ---
[INFO] argLine set to -javaagent:/home/circleci/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/circleci/project/kms/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kms-samples ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/circleci/project/kms/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ kms-samples ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /home/circleci/project/kms/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kms-samples ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/circleci/project/kms/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ kms-samples ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/circleci/project/kms/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ kms-samples ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:report (report) @ kms-samples ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ kms-samples ---
[INFO] Building jar: /home/circleci/project/kms/target/kms-samples-1.0.0.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.20:integration-test (default) @ kms-samples ---
[INFO] Failsafe report directory: /home/circleci/project/kms/target/failsafe-reports
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.SnippetsIT
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.717 s <<< FAILURE! - in com.example.SnippetsIT
[ERROR] encryptDecrypt_encryptsAndDecrypts(com.example.SnippetsIT)  Time elapsed: 0.89 s  <<< ERROR!
com.google.api.client.googleapis.json.GoogleJsonResponseException: 
400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "The request cannot be fulfilled. Resource projects/java-docs-samples-testing/locations/global/keyRings/test-snippets-key-ring/cryptoKeys/test-snippets-crypto-key/cryptoKeyVersions/1 has crypto_key_version.state: DESTROYED, but ENABLED is required.",
    "reason" : "failedPrecondition"
  } ],
  "message" : "The request cannot be fulfilled. Resource projects/java-docs-samples-testing/locations/global/keyRings/test-snippets-key-ring/cryptoKeys/test-snippets-crypto-key/cryptoKeyVersions/1 has crypto_key_version.state: DESTROYED, but ENABLED is required.",
  "status" : "FAILED_PRECONDITION"
}
	at com.example.SnippetsIT.encryptDecrypt_encryptsAndDecrypts(SnippetsIT.java:263)

[INFO] Running com.example.QuickstartIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.212 s - in com.example.QuickstartIT
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SnippetsIT.encryptDecrypt_encryptsAndDecrypts:263 » GoogleJsonResponse 400 Bad...
[INFO] 
[ERROR] Tests run: 9, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.20:verify (default) @ kms-samples ---
[INFO] Failsafe report directory: /home/circleci/project/kms/target/failsafe-reports

```

**Comment by White0ut** [comment]
Following up. It looks like there is no `set-primary-version` sample, and thus, new key versions aren't being set to primary during tests. This explains why the previous code parsed the active key version then manually called that version on encrypt calls.

Right now it looks like the test project has N key versions, and the primary is set to 1. I'll update these tests so each test does a "rotate", aka a create + set-primary.

**Pull request merged**
