### PR TITLE
Update AuthExample.java

### PR DESCRIPTION
**Pull request by JaredEzz**
wrap hardcoded string in Collections.singleton to allow Lists util to make a new ArrayList from it

When I tried to use this authExplicit example in IntelliJ IDEA, I was met with a static code analysis error and this change fixed it.

> It's a good idea to open an issue first for discussion.

- [ x] `pom.xml` parent set to latest `shared-configuration`
- [ x] Appropriate changes to README are included in PR
- [x ] API's need to be enabled to test (tell us)
- [ x] Environment Variables need to be set (ask us to set them)
- [x ] Tests pass (`mvn -P lint clean verify`)
  * (Note- `Checkstyle` passing is required; `Spotbugs`, `ErrorProne`, `PMD`, etc. `ERROR`'s are advisory only)
- [x ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by JaredEzz** [comment]
just signed the CLA

**Comment by JaredEzz** [comment]
@googlebot I signed it!

**Comment by lesv** [comment]
You might wish to import Collections if you really think this is a good idea.
```
------------------------------------------------------------
- testing auth
------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[ERROR] /tmpfs/src/github/java-docs-samples/auth/src/main/java/com/google/cloud/auth/samples/AuthExample.java:[53,44] cannot find symbol
  symbol:   variable Collections
  location: class com.google.cloud.auth.samples.AuthExample
```

**Comment by JaredEzz** [comment]
> You might wish to import Collections if you really think this is a good idea.
> 
> ```
> ------------------------------------------------------------
> - testing auth
> ------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [ERROR] /tmpfs/src/github/java-docs-samples/auth/src/main/java/com/google/cloud/auth/samples/AuthExample.java:[53,44] cannot find symbol
>   symbol:   variable Collections
>   location: class com.google.cloud.auth.samples.AuthExample
> ```

Whoops. Rookie mistake.

**Comment by JaredEzz** [comment]
I imported collections

**Pull request closed without merging**
