### PR TITLE
Adding Bigquery samples from /bigquery-samples-python

### PR DESCRIPTION
**Pull request by elibixby**
PTAL @GoogleCloudPlatform/devrel-samples

### CODE REVIEW

**Comment by tmatsuo** [comment]
Sorry for the late review. From my experience, asking review to a group doesn't usually work. Maybe you can assign a person for review next time.

Title says it's from /bigquery-samples-python. Isn't it java?
Can you add an env line to the .travis.yml so that travis run the tests?
You may want to cache the local maven directory.

**Comment by elibixby** [comment]
woops no worries. Yeah thought I had assigned someone. 

The name is legacy, as a couple samples are included into docs from here. The repository will be deleted once we get the docs updated (kimcam@ is working on them as we speak). 

Good thoughts on the travis changes. I avoided testing previously because travis struggles with multi-language repositories.

**Comment by elibixby** [comment]
@waprin Please add mvn tests to bigquery samples

**Comment by elibixby** [comment]
Closing as we now prefer merging from branches over forks.

**Pull request closed without merging**
