### PR TITLE
Excluded a property from the index

### PR DESCRIPTION
**Pull request by WalterHub**
For doc purposes

### CODE REVIEW

**Comment by WalterHub** [comment]
CLA is not applicable (I'm a Googler).

Thanks,
Walter

**Comment by lesv** [comment]
The line is 106 characters long it must be 100 or less characters - please fix.

**Comment by WalterHub** [comment]
Done, made line < 100 chars.

**Comment by lesv** [comment]
Not sure that passes our style guide, but I'm going to accept it.
LGTM

**Pull request merged**
