### PR TITLE
Fix broken appengine-gcs-client dependency.

### PR DESCRIPTION
**Pull request by tswast**
See: https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/127925475

### CODE REVIEW

**Comment by tswast** [comment]
Looks like it's going through. I think there was a bad version cached, based on the error message.

**Comment by tswast** [comment]
@lesv FYI

**Comment by lesv** [comment]
Sigh - missed that. :(  Old Maven stuff.

**Comment by lesv** [comment]
Thanks for fixing.

**Comment by lesv** [comment]
How did it ever pass?

**Pull request merged**
