### PR TITLE
Https

### PR DESCRIPTION
**Pull request by shun-fan**
Add https handlers to remaining samples

### CODE REVIEW

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
Please look at why travis failed.

**Comment by shun-fan** [comment]
It's an issue with sparkjava demo from Ajay on Ludo's team.

**Comment by ajkannan** [comment]
It looks like a flaky test because of a concurrency issue.  Since Travis does two builds for each PR when merging one upstream branch into another, there could be interleavings in interactions with Datastore that result in tests failing.  I will create a PR to fix this.

**Pull request merged**
