### PR TITLE
fix: change return type to List

### LINKED ISSUE #3828: spanner: return type of toListAsync changed
```
[ERROR] /tmpfs/src/github/java-docs-samples/spanner/cloud-client/src/main/java/com/example/spanner/AsyncQueryToListAsyncExample.java:[72,31] error: incompatible types: no instance(s) of type variable(s) T exist so that ApiFuture<List<T>> conforms to ApiFuture<ImmutableList<Album>>
  where T is a type-variable:
    T extends Object declared in method <T>toListAsync(Function<StructReader,T>,Executor)
```

https://github.com/GoogleCloudPlatform/java-docs-samples/pull/3823

### PR DESCRIPTION
**Pull request by olavloite**
Fixes #3828 and the build error in #3823

### CODE REVIEW

**Comment by olavloite** [comment]
The build error seems to be caused by https://github.com/googleapis/java-spanner/issues/456.

**Comment by lesv** [comment]
This doesn't compile.

**Comment by olavloite** [comment]
> This doesn't compile.

Are you sure? It compiles for me locally, and as far as I can see the CI builds do compile, but they currently all fail with the following exception:

```
[ERROR] com.example.spanner.SpannerSampleIT.testSample  Time elapsed: 347.502 s  <<< ERROR!
com.google.cloud.spanner.SpannerException:
INVALID_ARGUMENT: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid ListBackupOperations request.
field_violations {
  field: "filter"
  description: "Cannot evaluate filter expression: (metadata.database:projects/java-docs-samples-testing/instances/default-instance/databases/mysample-70ade011-8929-4521-a) AND (metadata.@type:type.googleapis.com/google.spanner.admin.database.v1.CreateBackupMetadata).\nType not found: type.googleapis.com/google.spanner.admin.database.v1.CreateBackupMetadata"
}

	at com.example.spanner.SpannerSampleIT.runSample(SpannerSampleIT.java:61)
	at com.example.spanner.SpannerSampleIT.testSample(SpannerSampleIT.java:273)
```

That exception is unfortunately caused by a known backend issue (see https://github.com/googleapis/nodejs-spanner/issues/1243#issuecomment-700404921)

**Comment by lesv** [comment]
Poor language choice.  I should have said it isn't running.

**Review by lesv — APPROVED** [review]

**Comment by lesv** [comment]
I can't comment out the tests, if it passes, then ok to merge, if not, you'll need to do something.

**Comment by lesv** [comment]
I should have merged a few things before I force-ran earlier.  I'll let this finish then run again

**Comment by lesv** [comment]
I've added `force-run` again, but I think this needs to be rebased before it will pass tests. (ignore the bad test)

**Pull request merged**
