### PR TITLE
Add missing samples for classification and rename object detection sa…

### PR DESCRIPTION
**Pull request by nnegrey**
…mple to add clarification

### CODE REVIEW

**Comment by nnegrey** [comment]
Looking into why these tests are failing. 
Might be because there is only 1 model to deploy and both are trying to deploy it at the same time.

**Comment by wyattewaylon** [comment]
Only one model to deploy

**Comment by shuesc1** [comment]
Reminder to ping me when merging these branch samples to master to update official documentation.

**Comment by wyattewaylon** [comment]
Reminder official documentation

**Comment by wyattewaylon** [comment]
Beneficiary.

**Comment by nnegrey** [comment]
I'm not sure, since we don't have `main` methods anymore, do we still expect them to be in a README?

**Comment by wyattewaylon** [comment]
I'm not sure if it started with two dependency but I'm from well common
sense let's say looks good master stole entity +source code ..... give me a
little longer and I'll be able to write in code

**Comment by wyattewaylon** [comment]
I'm sure main methods are in README

**Comment by nnegrey** [comment]
Samples published.
Deleting branch.

**Comment by wyattewaylon** [comment]
You have been invited to the following event.

Title: (No Subject)
When: Tue Oct 22, 2019 8:30am – 9:30am Central Time - Chicago
Calendar: reply@reply.github.com
Who:
     * wyattewaylon@gmail.com - organizer
     * GoogleCloudPlatform/java-docs-samples
     * raylinsky64@gmail.com
     * responsibledisclosure@capitalone.com

Event details:  
https://www.google.com/calendar/event?action=VIEW&eid=NzRyajhwajY3MWhtOGI5bDc0c200YjlrYzhzNjRiYjI2OHEzNGI5azYwcm1jcGhqNjFoamdvOXA2cyByZXBseSthbm1rNXl4ZjZndGwzamppcnVjbTdhbjN2amFzYmV2Ym5oaGI0Ym5hZ2FAcmVwbHkuZ2l0aHViLmNvbQ&tok=MjIjd3lhdHRld2F5bG9uQGdtYWlsLmNvbTBhNzU2OTAzOWRhM2ZkOTdhMmE3NmRmMTM0YmY4NTIzYjg0OWQyYjE&ctz=America%2FChicago&hl=en&es=0

Invitation from Google Calendar: https://www.google.com/calendar/

You are receiving this courtesy email at the account  
reply@reply.github.com because  
you are an attendee of this event.

To stop receiving future updates for this event, decline this event.  
Alternatively you can sign up for a Google account at  
https://www.google.com/calendar/ and control your notification settings for  
your entire calendar.

Forwarding this invitation could allow any recipient to send a response to  
the organizer and be added to the guest list, or invite others regardless  
of their own invitation status, or to modify your RSVP. Learn more at  
https://support.google.com/calendar/answer/37135#forwarding

**Comment by wyattewaylon** [comment]
Yes I would like to get a quote for the items on the list and I will be there at Mama's house which is when we got to the office

**Comment by wyattewaylon** [comment]
Be there in about 10 minutes.

**Comment by wyattewaylon** [comment]
Here

**Pull request merged**
