### PR TITLE
Make each speech sample independent

### PR DESCRIPTION
**Pull request by jerjou**

### CODE REVIEW

**Comment by jerjou** [comment]
@dpebot would you mind merging once Travis says it's okay?

**Comment by jerjou** [comment]
@dpebot? can you please merge when Travis is green?

**Comment by tswast** [comment]
Looks like the Travis failure is for Vision API. Go ahead and merge since the failure isn't related to this change.

```
 FaceDetectAppIT.detectFaces_badImage_throwsException:64 Not true that IOException message (<"image-annotator::bad image data.: image processing error!">) contains <"malformed request">
```

The error message for bad image data has changed. (Used to be malformed request)

**Comment by lesv** [comment]
This sample uses an old version of boringSSL.   Should not have been LGTM'd

**Comment by lesv** [comment]
Well, that's too strong -- it would be good to upgrade it, however.

**Comment by jerjou** [comment]
Hm... the pom lists 1.1.33.Fork23, which [seems to be](http://search.maven.org/#search%7Cga%7C1%7Cboringssl) the latest, no?

**Comment by jerjou** [comment]
plus, isn't that dpebot's job? :)

**Comment by lesv** [comment]
That's Ok, but all the stuff around it is wrong.  See https://github.com/grpc/grpc-java/blob/master/SECURITY.md

DPE Bot doesn't change things that don't come from a property.

**Pull request merged**
