### PR TITLE
Chc conditions

### PR DESCRIPTION
**Pull request by noerog**

### CODE REVIEW

**Comment by noerog** [comment]
We've had a bunch of conversations internally about this and this is the best workaround we have at the moment.

**Comment by noerog** [comment]
Hi lesv@, the client library actually can support this. Just updated and re-committed.

**Comment by noerog** [comment]
Hi lesv@, is there anything I need to do to get this merged?

**Comment by lesv** [comment]
Get it to pass Java 8

**Comment by noerog** [comment]
Is dpe@ bot supposed to have merged this?

**Comment by lesv** [comment]
It should have - one more try
@dpebot merge when green

**Comment by lesv** [comment]
But DPEbot doesn't appear to be listening @kurtisvg FYI
I'll try to remember to do it when the tests pass.

**Comment by lesv** [comment]
Sort of like DPEBot. 👍

**Pull request merged**
