### PR TITLE
Update test language to be more negative.

### PR DESCRIPTION
**Pull request by jerjou**

### CODE REVIEW

**Comment by tswast** [comment]
Nice.

**Comment by tswast** [comment]
Funny, it has negative polarity, but magnitude is only 0.3.

**Comment by jerjou** [comment]
Man - I gotta up my game...

**Comment by tswast** [comment]
Adding "That was the worst performance I've seen in a long time." to yours ups it to 1.2.

**Comment by jerjou** [comment]
...the API clearly was trained in high society, rather than in schoolyard playgrounds after class...

**Comment by lesv** [comment]
Please defer to Tim's language

**Comment by jerjou** [comment]
Done

**Pull request merged**
