### PR TITLE
Update Endpoints samples:

### PR DESCRIPTION
**Pull request by sepehre**
1. Change default service names to the new cloud.goog format.
2. Change app.yaml beta_settings to endpoints_api_service.

### CODE REVIEW

**Comment by lesv** [comment]
Travis says:
```
[ERROR]   The project com.google.cloud.speech:grpc-sample:1.0 (/home/travis/build/GoogleCloudPlatform/java-docs-samples/speech/grpc/pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin kr.motd.maven:os-maven-plugin:1.4.1.Final or one of its dependencies could not be resolved: Failed to read artifact descriptor for kr.motd.maven:os-maven-plugin:jar:1.4.1.Final: Could not transfer artifact kr.motd.maven:os-maven-plugin:pom:1.4.1.Final from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/kr/motd/maven/os-maven-plugin/1.4.1.Final/os-maven-plugin-1.4.1.Final.pom , ReasonPhrase:Forbidden. -> [Help 2]
```

**Comment by lesv** [comment]
I'll let you fix and then I'll review.

**Comment by sepehre** [comment]
I actually have no idea how to debug this Travis failure, does it not seem unrelated to this change?

**Comment by lesv** [comment]
Prior review said DO NOT MERGE until docs are coordinated. Once Sepehre asks, it's ok to merge. @tswast @jerjou

**Comment by sepehre** [comment]
Please merge.

**Pull request merged**
