### PR TITLE
bigtable (docs): add datasets for change stream tutorials in the docs

### PR DESCRIPTION
**Pull request by billyjacobson**
## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by Sita04** [comment]
@billyjacobson Considering the size of this dataset, can it be stored in a db and pulled when the tests need them?

**Comment by billyjacobson** [comment]
> @billyjacobson Considering the size of this dataset, can it be stored in a db and pulled when the tests need them?

The data is for a tutorial in the docs and needs to be imported for users. There isn't any code that goes with it since the user would just import the data and then uses a dataflow template, bigquery and looker. There isn't really another way to get data into Bigtable easily, and I'd rather not create an entirely new repo for this or put it somewhere else because it ends up being more difficult to keep track of. Happy to discuss

**Comment by minherz** [comment]
> > @billyjacobson Considering the size of this dataset, can it be stored in a db and pulled when the tests need them?
> 
> The data is for a tutorial in the docs and needs to be imported for users. There isn't any code that goes with it since the user would just import the data and then uses a dataflow template, bigquery and looker. There isn't really another way to get data into Bigtable easily, and I'd rather not create an entirely new repo for this or put it somewhere else because it ends up being more difficult to keep track of. Happy to discuss

Can you add arguments about the need for 10K of data records (in 2023 file)? I also don't think the solution of using this repo as a storage for tutorial data is the right solution. Please, consider using a designated storage bucket.

**Review by minherz — CHANGES_REQUESTED** [review]
Please downgrade the size of the CSV files to few dozen of records. Addressing the [comment][1] regarding the use of this data for tutorial, the use of this repo for storing content other than code for tutorials is possible to the reasonable extend.
Storing CSV file with 10K records does not look like one. Please, consider using one of DevRel projects to store the data in the publicly available storage bucket.

[1]: https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8962#issuecomment-1883073237

**Comment by billyjacobson** [comment]
Added to a bucket with bigtable public datasets

**Pull request closed without merging**
