### PR TITLE
[DO_NOT_MERGE] AutoML Tables

### PR DESCRIPTION
**Pull request by sirtorry**
"In September, these PRs (the [DO NOT MERGE] AutoML PRs) will be closed ~ this'll happen after updated, generated versions of these samples are published to the website (via google-cloud-java samples/ directories)

Until then, they'll continue to hang around, mainly so that we remember not to delete the branches these are sent from (because they are being used to publish docs at the moment)" - Rebecca

### CODE REVIEW

**Comment by nnegrey** [comment]
In Process of being converted to auto-generated samples.

**Comment by beccasaurus** [comment]
👋 Hi! Giving an update on these. Saw them still sitting around and wanted to ping with status incase folks stumble upon these!

In September, these PRs (the [DO NOT MERGE] AutoML PRs) will be closed ~ this'll happen after updated, generated versions of these samples are published to the website (via google-cloud-python samples/ directories)

Until then, they'll continue to hang around, mainly so that we remember not to delete the branches these are sent from (because they are being used to publish docs at the moment)

Long story. But long story short – these are planned to be resolved this month.

**Comment by lesv** [comment]
ping - status please?

**Comment by nnegrey** [comment]
I believe we can close the PR, but the branches need to stick around as the docs reference them directly while we migrate them to a new location.

**Comment by nnegrey** [comment]
Closing.

I will be moving many of these this quarter to the `automl` folder created in this PR: I believe we can close the PR, but the branches need to stick around as the docs reference them directly while we migrate them to a new location.

Branch is currently referenced in docs.

**Pull request closed without merging**
