### PR TITLE
feat(gemini sdk): add  generativeaionvertexai complex function calling 

### PR DESCRIPTION
**Pull request by TetyanaYahodska**
## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] **Tests** pass:   `mvn clean verify` **required**
- [x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by TetyanaYahodska** [comment]
Added complex response from some external API

**Review by Sita04 — APPROVED** [review]

**Comment by Sita04** [comment]
@TetyanaYahodska kindly wait for a review from @gericdong before merging.

**Review by glaforge — APPROVED** [review]
This looks great to me!

Non critical nit, unrelated to the key aspect of the sample, but `List.of()` might fail in CI as it's from JDK 9+. But I think it's fine to stick to it, it's nicer to read 😀

**Comment by Sita04** [comment]
@TetyanaYahodska Please address the lint issue.

**Pull request merged**
