### PR TITLE
Add missing email content

### PR DESCRIPTION
**Pull request by akerekes**
Without this line the code does not work.

### CODE REVIEW

**Comment by akerekes** [comment]
@frankyn @lesv PTAL

**Comment by lesv** [comment]
Thanks.

**Comment by lesv** [comment]
@dpebot merge when green

**Comment by akerekes** [comment]
@lesv do I need to do something to trigger the circleci build? It's been pending for days now.

**Comment by lesv** [comment]
@akerekes Nope - I'm looking into it.  I'll probably just merge once I've had a few minutes w/ Circle -- it will be 3:30 today at the latest.

**Pull request merged**
