### PR TITLE
Remove PowerMock from the Slack GCF sample.

### PR DESCRIPTION
**Pull request by saturnism**
Cherry-picked and rebased from @eamonnmcmanus's https://github.com/GoogleCloudPlatform/java-docs-samples/pull/2854

Instead of using Whitebox, use package-private constructor overloads
to supply the values needed by the test.

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [x] `pom.xml` parent set to latest `shared-configuration`
- [x] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [x] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by lesv** [comment]
@saturnism Looks like there are both Lint issues and Java 11.
Please follow the suggestions in the template at the top.
 Tests pass: `mvn clean verify` required
 Lint passes: `mvn -P lint checkstyle:check` required
 Static Analysis: `mvn -P lint clean compile pmd:cpd-check spotbugs:check` advisory only

**Comment by saturnism** [comment]
there is NPE from the tests during local run. any tricks to get the test running locally?

**Comment by saturnism** [comment]
> Lint passes: `mvn -P lint checkstyle:check` required
> Static Analysis: `mvn -P lint clean compile pmd:cpd-check spotbugs:check` advisory only

any way to simply add these into the compile phase, or add a profile to run these easily?

**Comment by saturnism** [comment]
also, i don't think those tests passed in the past. I'm getting

```
[ERROR] This use of java/util/logging/Logger.warning(Ljava/lang/String;)V might be used to include CRLF characters into log messages [functions.SlackSlashCommand] At SlackSlashCommand.java:[line 70] CRLF_INJECTION_LOGS
```
This line was not changed in the PR.

```
[ERROR] Class functions.SlackSlashCommand does not implement a toString method [functions.SlackSlashCommand] At SlackSlashCommand.java:[lines 40-210] IMC_IMMATURE_CLASS_NO_TOSTRING
```
Why does this class needs a ToString?

**Comment by saturnism** [comment]
need `SLACK_TEST_SIGNATURE` to test locally w/ `verify`

**Comment by ace-n** [comment]
@saturnism followed up internally, check your email. 🙂

**Comment by saturnism** [comment]
Static Analysis failed with:
```
[ERROR] COMPILATION ERROR :
[ERROR] javac: invalid target release: 11
```

**Comment by lesv** [comment]
you can ignore static analysis, but not lint.

**Comment by saturnism** [comment]
@lesv all tests passing. i think there is a problem w/ the static analysis check due to jdk version. please merge, thnx!

**Comment by lesv** [comment]
That makes sense - we'll update that too.

**Pull request merged**
