### PR TITLE
Adds region tags to Java alerting sample

### PR DESCRIPTION
**Pull request by mtabasko**
Adds region tags to AlertSample.java, for extraction of doc samples without resorting to regexps.

### CODE REVIEW

**Comment by lesv** [comment]
@dpebot merge when green

**Comment by mtabasko** [comment]
Do I need to do something to get this merged? (Still relatively unfamiliar with the process around the GitHub repos. A similar change to the C# repo was merged days ago, and this one is holding me up. Please let me know if I need to do something else to nudge it along! Thanks.

**Comment by mtabasko** [comment]
Thanks!!

**Comment by lesv** [comment]
Normally it should have done it automatically.

@tswast @jonparrott @kurtisvg DPE bot appears to be slacking.

**Pull request merged**
