### PR TITLE
Helloworld with Gradle

### PR DESCRIPTION
**Pull request by saturnism**
Fixes #issue

> It's a good idea to open an issue first for discussion.

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [x] Appropriate changes to README are included in PR
- [x] API's need to be enabled to test (tell us)
- [x] Environment Variables need to be set (ask us to set them)
- [x] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by lesv** [comment]
@eamonnmcmanus @glaforge Please ping me once you've reviewed and I'll merge (if appopiate)

**Comment by saturnism** [comment]
removed `settings.gradle` that seems optional, and so seems the `jar` block.

**Comment by eamonnmcmanus** [comment]
> removed `settings.gradle` that seems optional, and so seems the `jar` block.

There is currently a bug whereby if you have `settings.gradle` then you must also have the `jar` block. Otherwise you get a mystifying error message about `workspace.jar` not existing. I'd suggest putting the `jar` back so users who put back a `settings.gradle` don't run into this.

**Comment by saturnism** [comment]
will do

**Pull request merged**
