### PR TITLE
KMS: Make samples consistent with all languages.

### PR DESCRIPTION
**Pull request by White0ut**
In particular:

* Define keyRingId and cryptoKeyId consistently with the API.
* Use locationId as an argument.
* Use the language "ciphertext" and "plaintext" to refer to encrypted and unencrypted data, respectively.

I opted to keep file I/O in the Command runner to keep the API
clean, especially when being rendered on
https://cloud.google.com/kms/docs/encrypt-decrypt.

Tracking bug: http://b/64758639

### CODE REVIEW

**Comment by lesv** [comment]
@White0ut  I merged, but things didn't pass -- care to fix?  (tests don't run on forks :( )

```
[INFO] Building kms-samples 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kms-samples ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ kms-samples ---
[INFO] argLine set to -javaagent:/home/circleci/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/circleci/project/kms/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kms-samples ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/circleci/project/kms/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ kms-samples ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /home/circleci/project/kms/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kms-samples ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/circleci/project/kms/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ kms-samples ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/circleci/project/kms/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ kms-samples ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:report (report) @ kms-samples ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ kms-samples ---
[INFO] Building jar: /home/circleci/project/kms/target/kms-samples-1.0.0.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.20:integration-test (default) @ kms-samples ---
[INFO] Failsafe report directory: /home/circleci/project/kms/target/failsafe-reports
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.SnippetsIT
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 17.287 s <<< FAILURE! - in com.example.SnippetsIT
[ERROR] encryptDecrypt_encryptsAndDecrypts(com.example.SnippetsIT)  Time elapsed: 0.714 s  <<< ERROR!
com.google.api.client.googleapis.json.GoogleJsonResponseException: 
404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Location 'test-snippets-key-ring' not found.",
    "reason" : "notFound"
  } ],
  "message" : "Location 'test-snippets-key-ring' not found.",
  "status" : "NOT_FOUND"
}
	at com.example.SnippetsIT.encryptDecrypt_encryptsAndDecrypts(SnippetsIT.java:269)

[INFO] Running com.example.QuickstartIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.47 s - in com.example.QuickstartIT
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   SnippetsIT.encryptDecrypt_encryptsAndDecrypts:269 » GoogleJsonResponse 404 Not...
[INFO] 
[ERROR] Tests run: 9, Failures: 0, Errors: 1, Skipped: 0
```

Or let me know what I should do to fix your IT tests.

**Comment by lesv** [comment]
I looked on the project, and I have a global keyring w/ that name.

**Comment by White0ut** [comment]
re: google-cloud-java, do these snippets still belong there? If so I can migrate this code over there, lmk.

re: failing tests. I forgot to update the encrypt in that call. It's calling `encrypt(project, location, keyring, cryptokey, plaintext)` with `(project, keyring, cryptokey, keyversion, plaintext)`. 😞  Fix incoming!

**Comment by lesv** [comment]
Still fails :(

**Comment by lesv** [comment]
It's ok to keep them here since they are published.  I like them over there so that if something changes it breaks their world, before they publish, when we get the update it's been a while.

**Pull request merged**
