### PR TITLE
Update to latest versions of dependencies.

### PR DESCRIPTION
**Pull request by tswast**
I manually skipped the logging sample, since that sample is using the v1
APIs which are not compatible with the latest version v2 APIs.

### CODE REVIEW

**Comment by tswast** [comment]
@lesv PTAL.

This was auto-generated, but with the logging sample being v1 not v2, the tests didn't all pass. I took where it left off for this so we at least get most everything up to date.

**Comment by tswast** [comment]
Oops. It looks like one of the storage samples is using an old, incompatible version, too.

<details>
  <summary>Travis Logs: https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/142914888</summary>
```
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java:[19,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java:[20,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java:[48,17] cannot find symbol
[ERROR] symbol:   class Date
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferJobUtils
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java:[69,17] cannot find symbol
[ERROR] symbol:   class TimeOfDay
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferJobUtils
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferClientCreator.java:[24,47] package com.google.api.services.storagetransfer does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferClientCreator.java:[25,47] package com.google.api.services.storagetransfer does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferClientCreator.java:[43,17] cannot find symbol
[ERROR] symbol:   class Storagetransfer
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferClientCreator
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferClientCreator.java:[62,17] cannot find symbol
[ERROR] symbol:   class Storagetransfer
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferClientCreator
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[19,47] package com.google.api.services.storagetransfer does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[20,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[21,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[22,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[23,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[24,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[25,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[26,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[27,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[63,17] cannot find symbol
[ERROR] symbol:   class TransferJob
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[19,47] package com.google.api.services.storagetransfer does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[20,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[21,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[22,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[23,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[24,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[25,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[26,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[27,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[62,17] cannot find symbol
[ERROR] symbol:   class TransferJob
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/RequestChecker.java:[19,47] package com.google.api.services.storagetransfer does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/RequestChecker.java:[20,53] package com.google.api.services.storagetransfer.model does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/RequestChecker.java:[50,54] cannot find symbol
[ERROR] symbol:   class Storagetransfer
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.RequestChecker
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/RequestChecker.java:[50,17] cannot find symbol
[ERROR] symbol:   class ListOperationsResponse
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.RequestChecker
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java:[50,5] cannot find symbol
[ERROR] symbol:   class Date
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferJobUtils
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java:[50,17] cannot find symbol
[ERROR] symbol:   class Date
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferJobUtils
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java:[71,5] cannot find symbol
[ERROR] symbol:   class TimeOfDay
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferJobUtils
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferJobUtils.java:[71,22] cannot find symbol
[ERROR] symbol:   class TimeOfDay
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferJobUtils
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferClientCreator.java:[70,44] cannot find symbol
[ERROR] symbol:   variable StoragetransferScopes
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.TransferClientCreator
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/TransferClientCreator.java:[76,31] package Storagetransfer does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[65,5] cannot find symbol
[ERROR] symbol:   class Date
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[66,5] cannot find symbol
[ERROR] symbol:   class TimeOfDay
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[67,5] cannot find symbol
[ERROR] symbol:   class TransferJob
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[83,9] cannot find symbol
[ERROR] symbol:   class Schedule
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[81,27] cannot find symbol
[ERROR] symbol:   class GcsData
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[79,17] cannot find symbol
[ERROR] symbol:   class AwsAccessKey
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[75,13] cannot find symbol
[ERROR] symbol:   class AwsS3Data
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[72,9] cannot find symbol
[ERROR] symbol:   class TransferSpec
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[67,31] cannot find symbol
[ERROR] symbol:   class TransferJob
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[86,5] cannot find symbol
[ERROR] symbol:   class Storagetransfer
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/AwsRequester.java:[98,7] cannot find symbol
[ERROR] symbol:   class TransferJob
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.AwsRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[64,5] cannot find symbol
[ERROR] symbol:   class Date
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[65,5] cannot find symbol
[ERROR] symbol:   class TimeOfDay
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[66,5] cannot find symbol
[ERROR] symbol:   class TransferJob
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[79,22] cannot find symbol
[ERROR] symbol:   class Schedule
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[78,13] cannot find symbol
[ERROR] symbol:   class TransferOptions
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[76,13] cannot find symbol
[ERROR] symbol:   class ObjectConditions
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[74,27] cannot find symbol
[ERROR] symbol:   class GcsData
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[73,29] cannot find symbol
[ERROR] symbol:   class GcsData
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[71,9] cannot find symbol
[ERROR] symbol:   class TransferSpec
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[66,31] cannot find symbol
[ERROR] symbol:   class TransferJob
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[83,5] cannot find symbol
[ERROR] symbol:   class Storagetransfer
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/NearlineRequester.java:[95,7] cannot find symbol
[ERROR] symbol:   class TransferJob
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.NearlineRequester
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/storage/storage-transfer/src/main/java/com/google/cloud/storage/storagetransfer/samples/RequestChecker.java:[65,7] cannot find symbol
[ERROR] symbol:   class ListOperationsResponse
[ERROR] location: class com.google.cloud.storage.storagetransfer.samples.RequestChecker
[ERROR] -> [Help 1]
[ERROR] 
```
</details>

**Comment by lesv** [comment]
That is why we test. :)

**Comment by tswast** [comment]
Okay, I updated the PR to filter out a few more (mailjet, monitoring, storage. Going to give it another try.

**Comment by tswast** [comment]
@puneith @lesv  Ugh. Problem with Speech sample, already. :-(

```
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ grpc-sample ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 171 source files to /home/travis/build/GoogleCloudPlatform/java-docs-samples/speech/grpc/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /home/travis/build/GoogleCloudPlatform/java-docs-samples/speech/grpc/src/main/java/com/examples/cloud/speech/SyncRecognizeClient.java: Some input files use or override a deprecated API.
[WARNING] /home/travis/build/GoogleCloudPlatform/java-docs-samples/speech/grpc/src/main/java/com/examples/cloud/speech/SyncRecognizeClient.java: Recompile with -Xlint:deprecation for details.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/speech/grpc/src/main/java/com/examples/cloud/speech/AsyncRecognizeClient.java:[19,30] package com.google.auth.oauth2 does not exist
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/speech/grpc/src/main/java/com/examples/cloud/speech/AsyncRecognizeClient.java:[88,5] cannot find symbol
  symbol:   class GoogleCredentials
  location: class com.examples.cloud.speech.AsyncRecognizeClient
[ERROR] /home/travis/build/GoogleCloudPlatform/java-docs-samples/speech/grpc/src/main/java/com/examples/cloud/speech/AsyncRecognizeClient.java:[88,31] cannot find symbol
  symbol:   variable GoogleCredentials
  location: class com.examples.cloud.speech.AsyncRecognizeClient
[INFO] 3 errors 
```

**Comment by tswast** [comment]
It's green! We'll need to update the java-repo-tools to ignore the libraries with breaking changes until we can get the sample updated.

We should fix the speech sample, though, to use the latest version.

**Comment by lesv** [comment]
@puneith Welcome to Java -- When you checkin or update a sample, you want to update the pom to the latest of everything.  :(

**Comment by lesv** [comment]
LGTM

**Pull request merged**
