### PR TITLE
Stackdriver product rename

### PR DESCRIPTION
**Pull request by tmatsuo**
Renaming some APIs to Stackdriver brand

### CODE REVIEW

**Comment by tmatsuo** [comment]
This is not a test. Please feel free to merge.

**Comment by lesv** [comment]
LGTM - once I review Travis.

**Comment by lesv** [comment]
```
[WARNING] Could not transfer metadata com.google.api-client:google-api-client-appengine/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org: unknown error
[WARNING] Could not transfer metadata com.google.http-client:google-http-client/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org
[WARNING] Could not transfer metadata com.google.http-client:google-http-client:1.23.0-SNAPSHOT/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org
[WARNING] Failure to transfer com.google.http-client:google-http-client:1.23.0-SNAPSHOT/maven-metadata.xml from https://nexus.codehaus.org/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of codehaus-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata com.google.http-client:google-http-client:1.23.0-SNAPSHOT/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org
[WARNING] Could not transfer metadata com.google.http-client:google-http-client-parent:1.23.0-SNAPSHOT/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org
[WARNING] Could not transfer metadata com.google.http-client:google-http-client-jackson2/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org
[WARNING] Could not transfer metadata com.google.http-client:google-http-client-jackson2:1.23.0-SNAPSHOT/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org
[WARNING] Failure to transfer com.google.http-client:google-http-client-jackson2:1.23.0-SNAPSHOT/maven-metadata.xml from https://nexus.codehaus.org/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of codehaus-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata com.google.http-client:google-http-client-jackson2:1.23.0-SNAPSHOT/maven-metadata.xml from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org
```
and
```
[INFO] --- maven-checkstyle-plugin:2.17:check (default) @ cloud-logging-samples ---
[INFO] Starting audit...
/home/travis/build/GoogleCloudPlatform/java-docs-samples/logging/src/main/java/ListLogs.java:102: error: Line is longer than 100 characters (found 102).
```

Could you fix the line length issue?

**Comment by lesv** [comment]
The warnings are for the Images api.

**Comment by lesv** [comment]
@tmatsuo You exceeded the 100 character line length.

```
/home/travis/build/GoogleCloudPlatform/java-docs-samples/logging/src/main/java/ListLogs.java:102: error: Line is longer than 100 characters (found 102).
```

**Pull request closed without merging**
