### PR TITLE
Add newest model CLOUD_1 to avoid customers getting CUDA errors with …

### PR DESCRIPTION
**Pull request by DanElias**
…older models.

## Description

Fixes 295122561

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [ X] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [ ] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Review by gericdong — APPROVED** [review]
LGTM

**Review by lesv — APPROVED** [review]

**Comment by lesv** [comment]
# Java 11
```
#
# aiplatform
#

[0.001s][warning][os,container] Duplicate cpuset controllers detected. Picking /sys/fs/cgroup/cpuset, skipping /tmpfs/docker/overlay2/fe17b4659a1401f86f5abe05c7b62430d8a96414472e30be9fbfc36fe2acdd74/merged/sys/fs/cgroup/cpuset.
[ERROR] COMPILATION ERROR :
[ERROR] /tmpfs/src/github/java-docs-samples/aiplatform/src/main/java/aiplatform/CreateTrainingPipelineImageObjectDetectionSample.java:[76,38] cannot find symbol
  symbol:   variable CLOUD_1
  location: class com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMlImageObjectDetectionInputs.ModelType
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project aiplatform-snippets: Compilation failure
[ERROR] /tmpfs/src/github/java-docs-samples/aiplatform/src/main/java/aiplatform/CreateTrainingPipelineImageObjectDetectionSample.java:[76,38] cannot find symbol
[ERROR]   symbol:   variable CLOUD_1
[ERROR]   location: class com.google.cloud.aiplatform.v1beta1.schema.trainingjob.definition.AutoMlImageObjectDetectionInputs.ModelType
```

**Comment by lesv** [comment]
It's likely you need to update the pom.xml to use a different version of the client library.

**Comment by lesv** [comment]
@DanElias PTAL

**Comment by kweinmeister** [comment]
@DanElias do you still want to complete this PR, or should we close it?

**Comment by DanElias** [comment]
Won't fix

**Pull request closed without merging**
