### PR TITLE
Update java8 tests to run against java11

### PR DESCRIPTION
**Pull request by averikitsch**
Sample edits to force sample run.

### CODE REVIEW

**Comment by kurtisvg** [comment]
I see the following:
```
Skipping tests: Java version (${java.version}) not required (1.8, 11)
```

**Comment by kurtisvg** [comment]
Looks like you've found a flaw in our test script - it's not running in either project because a property is being used to pass in the java version. 

We should probably add a specific check for if the $JAVA_POM isn't something we expect and make sure that we log that it's invalid and either fail or run the test anyway.

**Comment by averikitsch** [comment]
Can I hard code the values we expect?

**Comment by kurtisvg** [comment]
> Can I hard code the values we expect?

Yeah that seems reasonable.

**Comment by averikitsch** [comment]
I've removed the sample. The one I chose is broken so I added an issue #2030

**Pull request merged**
