### PR TITLE
automl/cloud-client/pom.xml to use the GCP Libraries BOM 10.0.0

### LINKED ISSUE #3673: automl/cloud-client/pom.xml to use the latest GCP Libraries BOM
My followup of https://github.com/GoogleCloudPlatform/java-docs-samples/issues/3654. As per @lesv tests fail due to the upgrade. I'll troubleshoot the problem further.

## In which file did you encounter the issue?

./automl/cloud-client/pom.xml

```
suztomo-macbookpro44% find . -name pom.xml |xargs grep -A 3 '<artifactId>libraries-bom'
./video/beta/pom.xml:        <artifactId>libraries-bom</artifactId>
./video/beta/pom.xml-        <version>10.0.0</version>
...
--
./translate/cloud-client/pom.xml:        <artifactId>libraries-bom</artifactId>
./translate/cloud-client/pom.xml-        <version>9.1.0</version>
./translate/cloud-client/pom.xml-        <type>pom</type>
./translate/cloud-client/pom.xml-        <scope>import</scope>
--
...
./automl/cloud-client/pom.xml:        <artifactId>libraries-bom</artifactId>
./automl/cloud-client/pom.xml-        <version>7.0.2</version>
...
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #3673 

> It's a good idea to open an issue first for discussion.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Review by lesv — APPROVED** [review]

**Comment by suztomo** [comment]
Kokoro CI - Java 11 failed:

```
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 4.999783579s. [buffered_nanos=12119208, buffered_nanos=15407681, remote_addr=automl.googleapis.com/74.125.142.95:443]
```

**Comment by suztomo** [comment]
49937c3 (libraries-bom 9.1.0) passed "Kokoro CI - Java 11". Just lucky?

**Comment by suztomo** [comment]
49937c3 (libraries-bom 10.0.0) failed "Kokoro CI - Java 11 ":

```
Caused by: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: No other operations should be working on
 projects/233822521623/locations/us-central1/datasets/TRL5394674636845744128.
Currently running operations on the dataset:
	projects/233822521623/locations/us-central1/operations/TRL9210038809100550144
Call List Operation API to learn more details.
```

**Review by lesv — APPROVED** [review]

**Comment by lesv** [comment]
It seems to have passed - feel free to merge or change from draft -> review and ping me.

**Comment by suztomo** [comment]
@lesv I just moved this PR out from draft. Would you merge this?

**Pull request merged**
