### PR TITLE
dataflow: avoid importing log4j at all

### PR DESCRIPTION
**Pull request by davidcavazos**
Remove any direct dependencies of log4j and use slf4j instead, as recommended by the [documentation](https://cloud.google.com/dataflow/docs/guides/logging#java_1), and update to Beam 2.34 which doesn't depend on log4j.

Confirmed with `mvn dependency:tree | grep log4j-api` that there are no direct or indirect dependency instances of log4j on any sample by doing this.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by davidcavazos** [comment]
Hopefully fixes #5875

**Review by lesv — APPROVED** [review]

**Review by anguillanneuf — APPROVED** [review]

**Comment by anguillanneuf** [comment]
You may need to drop the beam version for some of these samples for tests to pass.

**Comment by davidcavazos** [comment]
Fixed lint issues. For the spanner sample, I'm trying Beam 2.32, if that passes I'll try 2.33 since we know something's broken with 2.34.

**Comment by davidcavazos** [comment]
I noticed that the Spanner sample was using Java 8, which [ends its support in 3 months](https://endoflife.date/java). Updating to Java 11, maybe that'll fix the failing tests as well.

**Comment by davidcavazos** [comment]
Java 11 didn't fix the tests, but downgrading to Beam 2.33 works for now. We still need to investigate why Beam 2.34 breaks SpannerIO.

cc: @jsimonweb @skuruppu @ansh0l -- tests for the SpannerIO sample with Beam 2.34 are still a blocker to upgrade versions (#5875)

**Comment by ansh0l** [comment]
@davidcavazos I will investigate separately on beam 2.34 issue. I'm assuming that for now, things are working with beam 2.33 in place.

**Pull request merged**
