### PR TITLE
fix: SampleTests: customAttributeSampleTest

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixing this issue: https://github.com/GoogleCloudPlatform/java-docs-samples/issues/2261

Since there is Thread.sleep(10000) in the main, the problem is that JUnit needs to wait until the whole thing is finished.

### CODE REVIEW

**Comment by lesv** [comment]
Mike - can you also bring the client library up to date (for v3)?

**Comment by munkhuushmgl** [comment]
> Mike - can you also bring the client library up to date (for v3)?

Okay, I will do that here

**Comment by munkhuushmgl** [comment]
> Mike - can you also bring the client library up to date (for v3)?

I may have misunderstood what you meant by updating the client library. 
Could you be bit more descriptive on updating the client library?

**Comment by munkhuushmgl** [comment]
> > Mike - can you also bring the client library up to date (for v3)?
> 
> I may have misunderstood what you meant by updating the client library.
> Could you be bit more descriptive on updating the client library?

library version is already up-to-date.

**Pull request merged**
