### PR TITLE
fix: update workflows quickstart to use env vars for config

### PR DESCRIPTION
**Pull request by grant**
Workflows Quickstart: enable env vars so docs can use this format.

---

Tested locally. Examples:

```
# Project config
GOOGLE_CLOUD_PROJECT=serverless-com-demo mvn compile exec:java -Dexec.mainClass=com.example.workflows.WorkflowsQuickstart

# Full config
GOOGLE_CLOUD_PROJECT=serverless-com-demo LOCATION=us-central1 WORKFLOW=myFirstWorkflow mvn compile exec:java -Dexec.mainClass=com.example.workflows.WorkflowsQuickstart

# Test
GOOGLE_CLOUD_PROJECT=serverless-com-demo mvn clean verify
```

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [x] `pom.xml` parent set to latest `shared-configuration`
- [x] Appropriate changes to README are included in PR
- [x] API's need to be enabled to test (tell us)
- [x] Environment Variables need to be set (ask us to set them)
- [x] **Tests** pass:   `mvn clean verify` **required**
- [x] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [x] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by averikitsch** [comment]
This goes against our sample guidelines for Java

**Comment by lesv** [comment]
EnvVar's make it easier to run, but your removing the pedagogical tool that actually helps folks understand how to use the sample.  I've added @kurtisvg since he participated in the UXR work that got this as our standard.

Once you've thought about that and if Kurtis comments, I'm ok with this if you insist.

**Comment by grant** [comment]
> This goes against our sample guidelines for Java

Hey Averi, thanks for the comment. Can you please specify the guideline? This PR mirrors using env vars rather than have a user try the code and gett . Env vars are used by Spark, BigTable, IoT and other samples this way.

For example:
- https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine-java8/tasks/quickstart/src/test/java/com/example/task/CreateTaskIT.java
- https://cloud.google.com/tasks/docs/quickstart#add_a_task_to_the_cloud_tasks_queue

The same does not run using the CloudSite instructions otherwise.

---

I can't tell if you're requesting changes or have a different solution.

**Comment by averikitsch** [comment]
There are older samples that don't fit the sample guidelines found at [SAMPLE_FORMAT.md](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md). We don't recommend using the CLI (exec:exec) or env vars in samples. Therefore the solution would be to revert these changes, so samples stay consistent. I'll defer to @kurtisvg though.

**Comment by grant** [comment]
OK. Running this program as-is produces a strange error unlike other quickstarts.

Specifically, users running this will see the quickstart not working. This is due to `"your-project-id"` as not a valid project. Other quickstarts don't have this required code change.

For context, the doc is here:
https://cloud.google.com/workflows/docs/quickstart-client-libraries

Should we have the docs have a new step just for Java? I'm okay with any suggestion, but the [current instructions](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/workflows/cloud-client/README.md) for running this sample are incomplete.

**Comment by grant** [comment]
Looks like Kurtis is gone for a month more, is there an alternate solution we want to allow this sample to work with instructions?

**Review by averikitsch — APPROVED** [review]
Since this is a quickstart, I will allow the env vars + CLI. For other samples please see go/code-snippets-style#running-from-the-command-line

**Comment by grant** [comment]
> Since this is a quickstart, I will allow the env vars + CLI. For other samples please see go/code-snippets-style#running-from-the-command-line

Understood, thanks!

**Pull request merged**
