### PR TITLE
cdn/signed-urls: use correct HMac algorithm

### LINKED ISSUE #8418: Cloud CDN url/cookie signing code samples use the wrong hash algorithm
Three files in `cdn/signed-urls` document use of the HMAC-SHA256 algorithm for signing URLs and cookies for use with Cloud CDN, but these features require use of the HMAC-SHA1 algorithm. The problems were introduced a few months ago in #8103, #8136, and #8183. They were introduced based on [discussion on a PR](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/8136#discussion_r1199391396) where it was asserted (correctly!) that HMAC-SHA256 is a more "recommended" algorithm than HMAC-SHA1. That's true when making choices when designing a new protocol, but that doesn't mean that these particular features allow you to just randomly choose an algorithm rather than using the one that Cloud CDN's servers expect.

I will file a PR to fix this.

### PR DESCRIPTION
**Pull request by glasser**
The Cloud CDN Signed URLs and Signed Cookies features expect signatures to be created with the HMAC-SHA1 algorithm; Google's servers validate signatures using this algorithm. PRs #8103, #8136, and #8183 updated the Java code samples to use HMAC-SHA256 instead, based on the argument that according to GCP's KMS docs on choosing a good algorithm, HMAC-SHA256 is recommended.

While it may be a better algorithm to use when designing a new system, it is not the algorithm used by the Signed URLs and Signed Cookies feature, so these code samples are currently 100% wrong and do not actually work to implement URL/cookie signing! (Fortunately the non-Java code samples are still correct.)

This PR reverts changes made in the above PRs to use the correct HMAC-SHA1 algorithm.

## Description

Fixes #8418

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [x] `pom.xml` parent set to latest `shared-configuration`
- [x] Appropriate changes to README are included in PR
- [x] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [x] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample 
- [x] Please **merge** this PR for me once it is approved

### CODE REVIEW

**Comment by glasser** [comment]
I don't have a proper Java environment set up in this repository on my computer with mvn etc so I have not run tests and I believe some of them will fail.  I was planning to just iterate on failures via CI although I suppose it does not actually run my tests until you allow them to or something.

**Comment by glasser** [comment]
@rsamborski Thanks! As I mentioned I hadn't gotten a dev environment working properly, so thanks for enabling CI for me. I think this change should fix it, though I guess you may have to ask it to run again?

**Comment by rsamborski** [comment]
Thank you for your contributions. I have requested the CI to rerun tests.

**Comment by glasser** [comment]
Yay, tests pass! :)

**Review by rsamborski — APPROVED** [review]

**Comment by rsamborski** [comment]
@glasser Our tooling picks up GitHub updates and publishes them automatically, but it may take a couple hours. I can already see the updated samples on cloud.google.com, but there might be some cache in place which affects what you see. Eventually it should get refreshed. Thanks for checking proactively.

**Pull request merged**
