### PR TITLE
Auto-update dependencies.

### PR DESCRIPTION
**Pull request by dzlier-gcp**
Same as #1098, but without update to apache beam version 2.4.0. Still working on that, but everything else passes fine.

### CODE REVIEW

**Comment by kurtisvg** [comment]
It looks like vision/beta/cloud-client is failing.

**Comment by dzlier-gcp** [comment]
I have seen it timeout like that before, I think it might be flakey. Let me try running it again and see if it succeeds.

**Comment by kurtisvg** [comment]
I rolled back the tests that were failing in PR #1098, then rebased this PR to reduce the time needed to run tests.

**Comment by dzlier-gcp** [comment]
Thanks for doing that - still not sure why this test is timing out now. Will look into that today.

**Comment by dzlier-gcp** [comment]
Added commit updating version of guava in newly failing tests.

**Comment by dzlier-gcp** [comment]
Tests pass, just need a LGTM.

**Pull request merged**
