### PR TITLE
Talent v4beta1 samples

### PR DESCRIPTION
**Pull request by nnegrey**
Keep branch until samples are move to master.

### CODE REVIEW

**Comment by lesv** [comment]
Ping - what's up?

**Comment by nnegrey** [comment]
I need to chat with Steve about handing this one off to get merged by product team.

**Comment by nnegrey** [comment]
Waiting on approval for docs update.

**Comment by lesv** [comment]
CLA is NO, just wondering what's up?

**Comment by lesv** [comment]
Over 30 days with no action -- care to comment?

**Comment by lesv** [comment]
@munkhuushmgl @nnegrey Can I close this?

**Comment by munkhuushmgl** [comment]
> @munkhuushmgl @nnegrey Can I close this?
Yes u can

**Pull request closed without merging**
