### PR TITLE
[logging] increase test timeout

### LINKED ISSUE #3578: com.example.logging.LoggingIT: testWriteAndListLogs failed
This test failed!

To configure my behavior, see [the Build Cop Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop).

If I'm commenting on this issue too often, add the `buildcop: quiet` label and
I will stop commenting.

---

commit: 82462e9802e74c4e898a0c0877c33cfb3465da3b
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/afe56bb1-6744-4487-b2d3-24ccd943367d), [Sponge](http://sponge2/afe56bb1-6744-4487-b2d3-24ccd943367d)
status: failed
<details><summary>Test output</summary><br><pre>org.junit.runners.model.TestTimedOutException: test timed out after 45000 milliseconds
	at com.example.logging.LoggingIT.testWriteAndListLogs(LoggingIT.java:88)
</pre></details>

### PR DESCRIPTION
**Pull request by averikitsch**
Fixes #3578

> It's a good idea to open an issue first for discussion.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by averikitsch** [comment]
This is still flaky. Investigating other approaches.

**Comment by lesv** [comment]
Apparently 60s is not enough
```
------------------------------------------------------------
- testing logging/cloud-client
------------------------------------------------------------
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 63.476 s <<< FAILURE! - in com.example.logging.LoggingIT
[ERROR] com.example.logging.LoggingIT.testWriteAndListLogs  Time elapsed: 60.019 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
	at com.example.logging.LoggingIT.testWriteAndListLogs(LoggingIT.java:88)

[ERROR] Errors:
[ERROR]   LoggingIT.testWriteAndListLogs:88 » TestTimedOut test timed out after 60000 mi...
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by averikitsch** [comment]
@simonz130 would you be concerned that logging listing is taking a very long time?

**Comment by simonz130** [comment]
> @simonz130 would you be concerned that logging listing is taking a very long time?

Yes, very concerned! Thanks for flagging this.
Can you try to run the same API via gcloud?
https://cloud.google.com/sdk/gcloud/reference/logging/logs/list
I wonder if it's library issue or BE issue.

**Comment by averikitsch** [comment]
Sorry, this is list log entries. Using `gcloud logging read  projects/PROJECT/logs/my-log` takes ~ 5 secs but using this sample takes around 4 minutes. I think I see a v2 logging library as well?

**Comment by averikitsch** [comment]
Closing since moved to https://github.com/googleapis/java-logging/pull/227/files

**Pull request closed without merging**
