### PR TITLE
Remove cloudsql for now

### PR DESCRIPTION
**Pull request by shun-fan**
Remove cloud sql as it's currently not supported for MVMs

### CODE REVIEW

**Comment by tswast** [comment]
Remove it from the root pom.xml as well.

**Comment by lesv** [comment]
LGTM once it's gone from the pom.xml, please take a look at travis as well.

**Comment by tswast** [comment]
LGTM. Looks like Travis is happy now that it's gone from the root pom.

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
Though it would be nice to see if we can make this work somehow.  I suspect we can, so please keep a copy.

**Comment by lesv** [comment]
Actually, we know it works as bookshelf works.

**Pull request merged**
