### PR TITLE
chore: add Kokoro build configs for JDK 17

### LINKED ISSUE #6197: Add sample tests for JDK 17
- Create a docker image for JDK 17 (Use Temurin)
- Add Kokoro jobs

### PR DESCRIPTION
**Pull request by shubha-rajan**
Fixes #6197 

Corresponding CL: [cl/445963302](https://critique.corp.google.com/cl/445963302)

### CODE REVIEW

**Comment by lesv** [comment]
@eaball35 @Neenu1995 FYI

**Review by lesv — APPROVED** [review]
So, you might wish to chat w/ @kurtisvg about this.  Just be sure that `pom.xml` requesting J17 don't get run w/ J8 or J11.  I'm not sure the code is that robust. (it might be)

**Comment by shubha-rajan** [comment]
> So, you might wish to chat w/ @kurtisvg about this. Just be sure that `pom.xml` requesting J17 don't get run w/ J8 or J11. I'm not sure the code is that robust. (it might be)

I think these lines make sure that only packages with a java version included in `JAVA_VERSION` will be included:
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/a49d10c4a3ba3e5f5b6263e4c7d8f8ddfd9bbc5a/.kokoro/tests/run_test_java.sh#L34-L39

**Comment by lesv** [comment]
SGTM

**Pull request merged**
