### PR TITLE
Fix auth sample to explicitly set the projectId

### PR DESCRIPTION
**Pull request by chingor13**
When explicitly setting credentials for a service, we should also advise the user to explicitly set their project id. `ServiceOptions` will not look for the project id in the service account json if provided (See https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3386). Instead, it will still use ADC's rules for finding the projectId with may or may not be what the user intends.

Context: internal b/110528397

### CODE REVIEW

**Comment by chingor13** [comment]
cc @jabubake

**Comment by jabubake** [comment]
@hostirosti @theacodes FYI

**Comment by hostirosti** [comment]
Can we hold back on this change? It doesn't address the underlying issue of inconsistent behavior between credentials provided via GOOGLE_APPLICATION_CREDENTIALS and .setCredentials(...) using the same service account credentials both times.

**Comment by kurtisvg** [comment]
@chingor13 @hostirosti Is this change still wanted? If not, are there any objections to closing the PR?

**Comment by hostirosti** [comment]
I lost track, but I believe the underlying issue was fixed iirc. Can you check with @theacodes around this? If the project id is picked up from the credentials this change is obsolete afaik.

**Pull request closed without merging**
