### PR TITLE
Modify the code samples for CJD

### PR DESCRIPTION
**Pull request by xinyunh0929**
Change JobServiceUtils to JobServiceQuickstart. Fix the error in previous sample and remove the samples related to deprecated fields.

### CODE REVIEW

**Comment by dzlier-gcp** [comment]
Looks like there's a compilation error. I'll re-add the kokoro test run label after that has been fixed.

**Comment by xinyunh0929** [comment]
Sorry, forgot to sync with GoogleCloudPlatform.

**Comment by xinyunh0929** [comment]
It's a backend issue. My teammate is fixing it. Would let you know when it is completed.

**Comment by xinyunh0929** [comment]
Issue in our backend should be fixed. May you rerun the tests?

**Pull request merged**
