### PR TITLE
Enable buildcop. 

### PR DESCRIPTION
**Pull request by kurtisvg**

### CODE REVIEW

**Comment by kurtisvg** [comment]
[Test Build](https://sponge.corp.google.com/invocation?id=ac4831c7-6398-4951-bc8a-405ece4ba795&searchFor&refreshSeconds=15)

**Comment by kurtisvg** [comment]
Fixes #2179

**Comment by lesv** [comment]
Build was Green, but had already been overridden.

**Comment by kurtisvg** [comment]
@lesv - I had manually triggered a "periodic" test to verify the bot is working. The presubumit tests won't trigger it to do anything.

**Pull request merged**
