### PR TITLE
WIP - Function - Helloworld Gradle - jar block

### PR DESCRIPTION
**Pull request by saturnism**
Fixes #issue

> It's a good idea to open an issue first for discussion.

- [x] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [x] Appropriate changes to README are included in PR
- [x] API's need to be enabled to test (tell us)
- [x] Environment Variables need to be set (ask us to set them)
- [x] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by lesv** [comment]
There are no files changed here.  I'm going to close.

**Comment by saturnism** [comment]
@lesv that's an obvious mistake, rather than closing, can we ping and resolve?

**Comment by lesv** [comment]
Sure, though

**Comment by lesv** [comment]
Or you can just reopen.  Which I did.

**Comment by lesv** [comment]
@saturnism Your title mentions WIP, but your PR isn't a DRAFT, I'm not quite sure what you want to do w/ this.  If you'd like me to merge, just ping.

**Comment by saturnism** [comment]
@lesv will do. I'm validating a couple of cases that @eamonnmcmanus had concerns with. i can convert it to draft.

**Pull request closed without merging**
