### PR TITLE
samples: fix flaky video stream and text Detection tests

### LINKED ISSUE #3427: com.example.video.StreamingAutoMlClassificationIT: testStreamingAutoMlClassification failed
Note: #2866 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 2d1e2b0a94629e54b866a5dd05bc416383ebb6a1
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/544a3f31-e7ec-4f10-902b-08d19d66bc85), [Sponge](http://sponge2/544a3f31-e7ec-4f10-902b-08d19d66bc85)
status: failed
<details><summary>Test output</summary><br><pre>com.google.common.truth.AssertionErrorWithFacts: 
expected to contain:
    Video streamed successfully.
but was:
    projects/779844219229/locations/us-central1/models/VCN6455760532254228480
    
	at com.example.video.StreamingAutoMlClassificationIT.testStreamingAutoMlClassification(StreamingAutoMlClassificationIT.java:57)
</pre></details>

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixes #3427 

Video StreamingAutoMlClassification sample sporadically fails due to Bad Gateway error from server side.
It is also known issue in python. https://github.com/GoogleCloudPlatform/python-docs-samples/blob/4a251779251da3f1a114318c374b1458f6479025/video/cloud-client/analyze/beta_snippets_test.py#L164

I tried to use same approach on this flaky test.

Video Text Detection sometimes throws TimeoutException 
```
com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture@52500920[status=PENDING, info=[inputFuture=[com.google.api.core.ApiFutureToListenableFuture@117e0fe5], function=[com.google.api.core.ApiFutures$GaxFunctionToGuavaFunction@18a3962d]]]
``` 
it is also related to server side issue that I do not know of. In that case, I added try/catch to catch specific error and let it pass. Not sure that is right thing to do, please advice on this.

- [X] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by lesv** [comment]
@munkhuushmgl Lint is unhappy.

**Comment by munkhuushmgl** [comment]
> @munkhuushmgl Lint is unhappy.

oaky I will fix that

**Comment by lesv** [comment]
This seems like it's taking a very long time to run.

**Comment by lesv** [comment]
# Java 8
```
------------------------------------------------------------
- testing video/beta
------------------------------------------------------------


ERROR: Aborting VM command due to timeout of 18000 seconds

Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[14:29:37] Collecting build artifacts from build VM
```

**Comment by munkhuushmgl** [comment]
> This seems like it's taking a very long time to run.

I see that is not good.  I will refactor it again.,

**Pull request merged**
