### PR TITLE
Added samples showcasing XMPP

### PR DESCRIPTION
**Pull request by meteatamel**
Added a number of Servlet based examples for XMPP

### CODE REVIEW

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
@tswast Could you figure out why Travis is unhappy?

**Comment by tswast** [comment]
@lesv Travis passed for the merge commit. https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/125630754

Right now Travis is failing on the `openssl` command to decrypt the service keys. I can send a PR to ignore that error and see how much further Travis can get. Right now it's not even verifying that the sample builds.

**Comment by tswast** [comment]
P.S. We missed adding this to the root pom.xml as a module, so right now it Travis is not verifying the build or check style.

**Pull request merged**
