### PR TITLE
fix: pom version recognization for tests

### PR DESCRIPTION
**Pull request by averikitsch**
Fixes #issue

> It's a good idea to open an issue first for discussion.

- [ ] I have followed [Sample Format Guide](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md)
- [ ] `pom.xml` parent set to latest `shared-configuration`
- [ ] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [ ] **Tests** pass:   `mvn clean verify` **required**
- [ ] **Lint**  passes: `mvn -P lint checkstyle:check` **required**
- [ ] **Static Analysis**:  `mvn -P lint clean compile pmd:cpd-check spotbugs:check` **advisory only**
- [ ] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by averikitsch** [comment]
@kolea2 This sample has not been running due to an issue with the specified Java version. It looks like it has issues with dependency versions, can your team take a look?

**Review by lesv — APPROVED** [review]
I wonder about the spaces in run_test_java.sh, but I'm presuming you've tested it. otherwise LGTM.

**Comment by lesv** [comment]
On the other hand, I notice that all 3 java versions are failing.  You might wish to upgrade to maven 3.9.1 for all build images.

**Comment by averikitsch** [comment]
The tests are failing because these samples tests have not been running due to the java version. Kokoro has not been flagging that the java version "8" is not expected.

**Pull request merged**
