### PR TITLE
Add Firebase Analytics sample

### PR DESCRIPTION
**Pull request by ace-n**
**Do not merge** until this is tested on GCF itself. (This is _blocked_ on a bug with the Analytics trigger itself.)

### CODE REVIEW

**Comment by lesv** [comment]
Ace - this appears to have been pushed on another PR, and there are conflicts, can it be closed?

**Comment by ace-n** [comment]
I'd rather keep it open until this sample is no longer blocked. We can
update it (and force-push on top of the new master) then.

**Comment by lesv** [comment]
ping

**Comment by ace-n** [comment]
This sample is on hold for now - followed up internally; see b/132733798
<https://buganizer.corp.google.com/132733798>

(I can update it to the new Functions sample format once we're sure
everything will work.)

**Pull request closed without merging**
