### PR TITLE
feat: update sample to use beam-side lite io

### PR DESCRIPTION
**Pull request by anguillanneuf**
Pub/Sub Lite [maintains](https://cloud.google.com/pubsub/docs/choosing-pubsub-or-lite#streaming_pipelines_2) two I/O connectors to Beam. 

This PR updates the original sample to use the Beam-side `PubsubLiteIO`.

Wait to merge this PR after getting approvals from the Pub/Sub Lite team.

---

Chatted with @manuelmenzella-google, let's wait to merge it after the Beam-side I/O is stable.

### CODE REVIEW

**Comment by anguillanneuf** [comment]
Is it possible to add https://github.com/orgs/googleapis/teams/api-pubsublite as a reviewer?

**Review by lesv — APPROVED** [review]

**Comment by lesv** [comment]
@api-pubsublite PLEASE REVEIW

**Comment by lesv** [comment]
@anguillanneuf I can't invite teams from another org, we can try to create a replicate team in this org, however.  Could you invite an individual to review this?  If you can't add them directly, you can mention them in a comment.

**Comment by anguillanneuf** [comment]
@lesv A replicate team for https://github.com/orgs/googleapis/teams/api-pubsublite is the best. 

I chatted with @manuelmenzella-google, we decided to punt on it until the I/O connector released with Beam is stable, which could be another month or two.

**Comment by lesv** [comment]
@anguillanneuf Looks like there needs to be some manual work at this point.

**Review by lesv — APPROVED** [review]

**Comment by lesv** [comment]
@anguillanneuf What's the plan for this?  Will it ever be merged or should we close it?

**Pull request merged**
