### PR TITLE
Move Datastore concepts to test directory so the tests actually run.

### PR DESCRIPTION
**Pull request by tswast**
@lesv ptal

### CODE REVIEW

**Comment by tswast** [comment]
Docs CL has approval. When should we check these in?

**Comment by lesv** [comment]
Tomorrow.

**Comment by tswast** [comment]
Okay, just as well. I want to verify that the tests are actually running before merging anyway. I think I might have to add the JUnit runwith annotation and/or rename the class with a Test suffix

**Comment by tswast** [comment]
My thoughts last night were correct. Moving the Concepts to the `test/` directory made the plugin not complain that the directory was missing, but it still didn't actually run them. Adding the Test suffix and the RunWith annotation they now run.

I'll update the docs CL to match this change, as well.

@lesv

**Pull request merged**
