### PR TITLE
automl: remove vision samples no longer on cgc

### PR DESCRIPTION
**Pull request by Strykrol**
- [ x] `pom.xml` parent set to latest `shared-configuration`
- [ in progress] Appropriate changes to README are included in PR
- [ ] API's need to be enabled to test (tell us)
- [ ] Environment Variables need to be set (ask us to set them)
- [see below] Tests pass (`mvn -P lint clean verify`)
- [x ] Please **merge** this PR for me once it is approved.

Need to take a look still at modelApi tests (it looks like the entire file is obviated, but could be refactored to test model creation?) Could use a second set of eyes here.

### CODE REVIEW

**Comment by lesv** [comment]
Anthony - please join the org at `github/` (internal site)

**Comment by lesv** [comment]
# Java 8
```
------------------------------------------------------------
- testing vision/automl
------------------------------------------------------------
     [java] JVM args ignored when same JVM is used.
[ERROR] Boxing/unboxing to parse a primitive com.google.cloud.vision.samples.automl.ModelApi.createModel(String, String, String, String, String) [com.google.cloud.vision.samples.automl.ModelApi, com.google.cloud.vision.samples.automl.ModelApi] At ModelApi.java:[line 76]Another occurrence at ModelApi.java:[line 79] DM_BOXED_PRIMITIVE_FOR_PARSING
[ERROR] com.google.cloud.vision.samples.automl.ModelApi.argsHelper(String[]) invokes System.exit(...), which shuts down the entire virtual machine [com.google.cloud.vision.samples.automl.ModelApi] At ModelApi.java:[line 126] DM_EXIT
[ERROR] Method com.google.cloud.vision.samples.automl.ModelApi.createModel(String, String, String, String, String) prints the stack trace to the console [com.google.cloud.vision.samples.automl.ModelApi] At ModelApi.java:[line 99] IMC_IMMATURE_CLASS_PRINTSTACKTRACE
[ERROR] Possible information exposure through an error message [com.google.cloud.vision.samples.automl.ModelApi] At ModelApi.java:[line 99] INFORMATION_EXPOSURE_THROUGH_AN_ERROR_MESSAGE
[ERROR] Method com.google.cloud.vision.samples.automl.ModelApi.createModel(String, String, String, String, String) converts String to primitive using excessive boxing [com.google.cloud.vision.samples.automl.ModelApi] At ModelApi.java:[line 76] NAB_NEEDLESS_BOXING_PARSE
[ERROR] Method com.google.cloud.vision.samples.automl.ModelApi.createModel(String, String, String, String, String) converts String to primitive using excessive boxing [com.google.cloud.vision.samples.automl.ModelApi] At ModelApi.java:[line 79] NAB_NEEDLESS_BOXING_PARSE
[ERROR] Method com.google.cloud.vision.samples.automl.ModelApi.argsHelper(String[]) defines parameter list with array as last argument, rather than vararg [com.google.cloud.vision.samples.automl.ModelApi] At ModelApi.java:[lines 109-142] UVA_USE_VAR_ARGS
[ERROR] com.google.cloud.vision.samples.automl.PredictionApi.argsHelper(String[]) invokes System.exit(...), which shuts down the entire virtual machine [com.google.cloud.vision.samples.automl.PredictionApi] At PredictionApi.java:[line 121] DM_EXIT
[ERROR] Method com.google.cloud.vision.samples.automl.PredictionApi.predict(String, String, String, String, String) prints the stack trace to the console [com.google.cloud.vision.samples.automl.PredictionApi] At PredictionApi.java:[line 96] IMC_IMMATURE_CLASS_PRINTSTACKTRACE
[ERROR] This API (java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path;) reads a file whose location might be specified by user input [com.google.cloud.vision.samples.automl.PredictionApi, com.google.cloud.vision.samples.automl.PredictionApi] At PredictionApi.java:[line 77]At PredictionApi.java:[line 126] PATH_TRAVERSAL_IN
[ERROR] Method com.google.cloud.vision.samples.automl.PredictionApi.argsHelper(String[]) defines parameter list with array as last argument, rather than vararg [com.google.cloud.vision.samples.automl.PredictionApi] At PredictionApi.java:[lines 106-135] UVA_USE_VAR_ARGS
[ERROR] COMPILATION ERROR :
[ERROR] /tmpfs/src/github/java-docs-samples/vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java:[56,13] cannot find symbol
  symbol:   method listModels(java.lang.String,java.lang.String,java.lang.String)
  location: class com.google.cloud.vision.samples.automl.ModelApi
[ERROR] /tmpfs/src/github/java-docs-samples/vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java:[64,13] cannot find symbol
  symbol:   method getModel(java.lang.String,java.lang.String,java.lang.String)
  location: class com.google.cloud.vision.samples.automl.ModelApi
[ERROR] /tmpfs/src/github/java-docs-samples/vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java:[71,13] cannot find symbol
  symbol:   method listModelEvaluations(java.lang.String,java.lang.String,java.lang.String,java.lang.String)
  location: class com.google.cloud.vision.samples.automl.ModelApi
[ERROR] /tmpfs/src/github/java-docs-samples/vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java:[79,13] cannot find symbol
  symbol:   method getModelEvaluation(java.lang.String,java.lang.String,java.lang.String,java.lang.String)
  location: class com.google.cloud.vision.samples.automl.ModelApi
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project vision-automl: Compilation failure: Compilation failure:
[ERROR] /tmpfs/src/github/java-docs-samples/vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java:[56,13] cannot find symbol
[ERROR]   symbol:   method listModels(java.lang.String,java.lang.String,java.lang.String)
[ERROR]   location: class com.google.cloud.vision.samples.automl.ModelApi
[ERROR] /tmpfs/src/github/java-docs-samples/vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java:[64,13] cannot find symbol
[ERROR]   symbol:   method getModel(java.lang.String,java.lang.String,java.lang.String)
[ERROR]   location: class com.google.cloud.vision.samples.automl.ModelApi
[ERROR] /tmpfs/src/github/java-docs-samples/vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java:[71,13] cannot find symbol
[ERROR]   symbol:   method listModelEvaluations(java.lang.String,java.lang.String,java.lang.String,java.lang.String)
[ERROR]   location: class com.google.cloud.vision.samples.automl.ModelApi
[ERROR] /tmpfs/src/github/java-docs-samples/vision/automl/src/test/java/com/google/cloud/vision/samples/automl/ModelApiIT.java:[79,13] cannot find symbol
[ERROR]   symbol:   method getModelEvaluation(java.lang.String,java.lang.String,java.lang.String,java.lang.String)
[ERROR]   location: class com.google.cloud.vision.samples.automl.ModelApi
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

 Testing failed: Maven returned a non-zero exit code.
```

**Comment by Strykrol** [comment]
@lesv - Joined org. I also removed the modelapi test entirely (something I pointed out in my initial comment).

**Comment by Strykrol** [comment]
@lesv - I merged the latest changes and resolved deletion conflicts.

**Pull request merged**
