### PR TITLE
Use long-flags everywhere, for readability.

### PR DESCRIPTION
**Pull request by kryzthov**
Prevents common mistake between -p and -P.

@navinger @p-buse

### CODE REVIEW

**Comment by kryzthov** [comment]
@lesv @broady Would you be able to take a look? Thanks!

**Comment by lesv** [comment]
@kryzthov Vision is failing so, I'm Ok w/ merging this.  Please confirm that you want that to happen.

**Comment by kryzthov** [comment]
Yes, please merge this change whenever you have a chance. Thanks!

**Comment by kryzthov** [comment]
Just rebased the branch on master.

**Pull request merged**
