### PR TITLE
Added gradle build configuration for endpoints-framework-v2/backend

### PR DESCRIPTION
**Pull request by mpoehler**
There was a gradle build configuration missing for endpoints-framework-v2/backend. I know that there is a gradle configuration in the migration folder, but [the Quickstart](https://cloud.google.com/endpoints/docs/frameworks/java/get-started-frameworks-java) brings new developers to the backend example which is really nice, because it ends up with curl-query to the deployed API. But after that it was tough for me to get it to work with gradle. For that reason I I added a gradle build configuration to the endpoints-framework-v2/backend 

I used the [Endpoints Framework Gradle Plugin](https://cloud.google.com/appengine/docs/standard/java/tools/gradle-endpoints-frameworks-plugin) in conjunction with the newer [Gradle App Engine Plugin] (https://cloud.google.com/appengine/docs/standard/java/tools/gradle) / 
https://github.com/GoogleCloudPlatform/app-gradle-plugin

It works similar to the maven version, also with a call to the deployed version to test it using curl. To get it clean, I split up the documentation in the README.md by build tool.

### CODE REVIEW

**Comment by lesv** [comment]
@frankyn PING

**Comment by frankyn** [comment]
Reviewing

**Comment by mpoehler** [comment]
Hi @frankyn, I made the requested changes. gradle.properties needs to be in version control on the project level, of course. Now it runs out-of-the-box.

**Comment by frankyn** [comment]
Thanks @mpoehler!

**Comment by mpoehler** [comment]
@frankyn Ok, I understand - no problem. I removed the wrapper and updated the README.

**Comment by frankyn** [comment]
Thanks!

**Pull request merged**
