### PR TITLE
Fix flaky test

### LINKED ISSUE #85: Build failing on Jenkins due to sparkdemo
This might be the same flakey failure we were seeing in Travis.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.google.appengine.sparkdemo.UserControllerTest
Feb 08, 2016 1:00:25 AM com.google.api.services.datastore.client.BaseDatastoreFactory makeClient
WARNING: Not using any credentials
Feb 08, 2016 1:00:28 AM com.google.api.services.datastore.client.BaseDatastoreFactory makeClient
WARNING: Not using any credentials
[Thread-1] INFO org.eclipse.jetty.util.log - Logging initialized @3035ms
[Thread-1] INFO spark.webserver.JettySparkServer - == Spark has ignited ...
[Thread-1] INFO spark.webserver.JettySparkServer - >> Listening on 0.0.0.0:8080
[Thread-1] INFO org.eclipse.jetty.server.Server - jetty-9.3.2.v20150730
[Thread-1] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@42c69b0e{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[Thread-1] INFO org.eclipse.jetty.server.Server - Started @3198ms
[main] INFO spark.webserver.JettySparkServer - >>> Spark shutting down ...
[main] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@42c69b0e{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[main] INFO spark.webserver.JettySparkServer - done
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.345 sec <<< FAILURE!
Running com.google.appengine.sparkdemo.UserServiceTest
Feb 08, 2016 1:00:33 AM com.google.api.services.datastore.client.BaseDatastoreFactory makeClient
WARNING: Not using any credentials
Feb 08, 2016 1:00:34 AM com.google.api.services.datastore.client.BaseDatastoreFactory makeClient
WARNING: Not using any credentials
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.119 sec

Results :

Failed tests:   testDeleteUser(com.google.appengine.sparkdemo.UserControllerTest): expected:<0> but was:<1>
```

### PR DESCRIPTION
**Pull request by ajkannan**
Fixes #85 

Each run of the UserControllerTest now creates a unique kind so that multiple builds occurring at once won't cause the integration tests to fail.

### CODE REVIEW

**Comment by tswast** [comment]
LGTM.

Looks like an okay solution to me. Should keep tests from stepping on each other in datastore, and it doesn't seem to complicate the sample any more (other than some command-line arg parsing, which looks fine)

**Comment by lesv** [comment]
LGTM

**Comment by lesv** [comment]
@tswast  - Why don't I see anything from travis?

**Comment by tswast** [comment]
@lesv They show up when I click "View Details" of the merged commit into `master` line.

https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/108140287
https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/108140285

**Comment by lesv** [comment]
Cool - thanks.

On Wed, Feb 10, 2016 at 10:00 AM, Tim Swast <notifications@github.com>
wrote:

> @lesv <https://github.com/lesv> They show up when I click "View Details"
> of the merged commit into master line.
>
>
> https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/108140287
>
> https://travis-ci.org/GoogleCloudPlatform/java-docs-samples/builds/108140285
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/java-docs-samples/pull/88#issuecomment-182505045>
> .
>



-- 


*  •  **Les Vogel*
*  •  *Cloud Developer Relations
*  •  *lesv@google.com
*  •  *+1-4 <%2B1-650-338-7103>08-676-7023

**Pull request merged**
